### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by ric96** [Unvanquished/Unvanquished#1015]
currently compiling for arm using gcc cross compile 6.3 from linaro gives the following error
CMake Error at daemon/cmake/DaemonFlags.cmake:185 (message):
  C++11 not supported by compiler

**Comment by mbasaglia** [comment]
Unvanquished does require C++11 so you won't be able to compile it unless you have a compiler supporting it. 
Now, it could also be an issue with CMake not recognizing the compiler. Looks like we have custom code for this: https://github.com/DaemonEngine/Daemon/blob/b6e41f7baae75adbd7121e70d7b73b7e19ec4b6a/cmake/DaemonFlags.cmake#L181-L187 instead of using CXX_STANDARD.

Can you try to invoke the compiler manually on an empty file or something passing -std=gnu++11 or -std=c++11 to see if it does support C++11?
Also make sure you have the C++ frontend for your compiler.

**Comment by ric96** [comment]
c++11 support seems to be working for me
no errors with aarch64-linux-gnu-g++  -std=c++11 -o test.o test.c
and
https://github.com/sloede/cxx11tests this passes

**Comment by mbasaglia** [comment]
That's good, so I guess it's just a matter of fixing our CMake scripts

**Comment by ric96** [comment]
should i just try a ghetto fix on https://github.com/DaemonEngine/Daemon/blob/b6e41f7baae75adbd7121e70d7b73b7e19ec4b6a/cmake/DaemonFlags.cmake#L181-L187 by bypassing the check?

**Comment by mbasaglia** [comment]
Well, that won't get merged but you can try to do it locally to see if you run into other issues

**Comment by mbasaglia** [comment]
@DolceTriade Do you know why we use gnu++11 instead of c++11?
Also, this is how I usually check for C++ version https://github.com/mbasaglia/CMake-Lib/blob/master/misc.cmake#L20-L39

**Comment by TimePath** [comment]
@mbasaglia iirc some older compilers supported gnu++11 but not c++11. We should probably check for c++11 first assuming we don't make use of any GNU extensions

**Comment by ric96** [comment]
update:
I tried manually bypassing c++11 check, work no more error for this but a new error appears 
-- Looking for pthread.h - not found

again works fine with aarch64-linux-gnu-g++ -std=c++11 -o test.o test.c with test.c now having 
```
#include <pthread.h>
```

**Comment by mbasaglia** [comment]
I assume the include paths for the cross compiler is different from the standard ones. Looking at CMake internals, you should be able to fix it by defining CMAKE_REQUIRED_INCLUDES.
I assume there might be some friendlier way to tell CMake you are cross-compiling but tbh I don't know much about this.

**Comment by ric96** [comment]
i doubt it's limited to cross compiling, i am getting the same issues of arm host systems, without any cross compilation

**Comment by ric96** [comment]
cmake output log http://paste.ubuntu.com/25232328/
cmake error log: http://paste.ubuntu.com/25232331/

**Comment by slipher** [comment]
Just a heads up, even if you do manage to compile on ARM you won't be able to do much. The servers only provide x86-* gamelogics.

**Comment by mbasaglia** [comment]
Does NaCl support ARM?

**Comment by ric96** [comment]
seems to be, https://blog.chromium.org/2013/01/native-client-support-on-arm.html
have close to no info on what nacl is though

**Comment by ric96** [comment]
@slipher I am just looking for a good opengl 3 test/benchmark platform, once better arm desktops appear then we can eventually have people host arm servers, but for now its a great graphics benchmark platform for opengl 3

**Comment by mbasaglia** [comment]
> have close to no info on what nacl is though

It's what we use for our game code

**Comment by slipher** [comment]
You'll need to have both client and server game logic running to get any graphics going. It is also possible to run these without NaCl, but hard to be sure it will work out of the box without a bit of hacking.

**Comment by illwieckz** [comment]
NaCl is the sandbox running game code (allowing servers to share custom code and having the players running that custom code in the sandbox).

If you only plan to build Unvanquished for benchmark purpose (not playing online), it's probably not a problem to run the game code/server code as shared libs.

You can pass `-DBUILD_GAME_NACL=0 -DBUILD_GAME_NACL_NEXE=0` options to _cmake_ before building, then `-set vm.cgame.type 3 -set vm.sgame.type 3` to _daemon_ engine once built.

This way you can load a complete local game without any NaCl bit. But you must not try to join some online server, because if the server uses a custom code, you will download the custom one but not run it, ending with mismatches.

By the way, I don't know if it's a good idea to benchmark Unvanquished without NaCl: the benchmark will probably not be trustful: the game is probably faster on shared libs than on NaCl sandbox, even if the sandbox runs very well. Well, I really don't know if the difference is measurable.

So, if you want to benchmark multiple architectures or systems, it's very OK, just be sure you always make the same kind of build for every system (like shared libs for every system), if you want to give a glance of the Unvanquished performance on an arbitrary platform and you don't use NaCl, well, it would be fair to mention the experience not used the common environment player uses.  As I said, I really don't know if the difference is measurable, but it would be honest to say the build was not standard, which is not a problem. :wink:

I would interesting to know if you manage to get a workable Unvanquished build running on NaCl on ARM64 though. :+1: 

Note: I recommend to not build the current master but to build the `v0.50.0` tag, this way you can use released 0.50.0 pk3 without having to care about anything.

**Comment by illwieckz** [comment]
NaCl is the sandbox running game code (allowing servers to share custom code and having the players running that custom code in the sandbox).

If you only plan to build Unvanquished for benchmark purpose (not playing online), it's probably not a problem to run the game code/server code as shared libs.

You can pass `-DBUILD_GAME_NACL=0 -DBUILD_GAME_NACL_NEXE=0` options to _cmake_ before building, then `-set vm.cgame.type 3 -set vm.sgame.type 3` to _daemon_ engine once built.

This way you can load a complete local game without any NaCl bit. But you must not try to join some online server, because if the server uses a custom code, you will download the custom one but not run it, ending with mismatches.

By the way, I don't know if it's a good idea to benchmark Unvanquished without NaCl: the benchmark will probably not be trustful: the game is probably faster on shared libs than on NaCl sandbox, even if the sandbox runs very well. Well, I really don't know if the difference is measurable.

So, if you want to benchmark multiple architectures or systems, it's very OK, just be sure you always make the same kind of build for every system (like shared libs for every system), if you want to give a glance of the Unvanquished performance on an arbitrary platform and you don't use NaCl, well, it would be fair to mention the experience not used the common environment player uses.  As I said, I really don't know if the difference is measurable, but it would be honest to say the build was not standard, which is not a problem. :wink:

I would interesting to know if you manage to get a workable Unvanquished build running on NaCl on ARM64 though. :+1: 

Note: I recommend to not build the current master but to build the `v0.50.0` tag, this way you can use the released 0.50.0 pk3 without having to care about anything.

**Comment by illwieckz** [comment]
Note that if you manage to build with NaCl, you probably only have to build the engine ([github.com/DaemonEngine/Daemon](https://github.com/DaemonEngine/Daemon)).

**Comment by slipher** [comment]
You'll have to build the gamelogic either way since no one is providing an ARM nexe. We run the PNaCl translator as part of the build process, not at runtime.

**Comment by illwieckz** [comment]
Oh yes, we are not yet using `pexe`…

**Comment by ric96** [comment]
still stuck at -- Looking for pthread.h - not found
I've even tried installing the cross compiler instead of simply adding it to the path

**Comment by illwieckz** [comment]
The current master branch of the engine can now be built for `armhf` (32-bit) and `arm64` (64-bit) on Linux, and we can now build arm nexe. Which means 0.54.0 will be usable on armhf and arm64 both as client and server on Linux.

**Comment by necessarily-equal** [comment]
Note that we are not sure we will be able to actually support armhf, because should we switch to WASM using [wasmtime](https://docs.wasmtime.dev/) to replace NaCl, we loose 32bits support. But ARM64 which is the subject of this issue should stay supported.

**Comment by illwieckz** [comment]
Also I forgot to mention there is a release-candidate to test with armhf and arm64 builds:
https://forums.unvanquished.net/viewtopic.php?t=2353 😉️

**Comment by DolceTriade** [comment]
Can you actually play Unv (not just get it running...) on a 32bit ARM machine? I'm pretty sure any device in this class is generally a SBC running at under 1 GHz and no GPU... Maybe its ok to not support armf and only support aarch64?

**Comment by illwieckz** [comment]
32-bit ARM is still the default and recommended operating system download for some devices, even if the hardware supports 64-bit. This includes the well known Raspberry Pi that can feature 4 cores and 8GB of ram and would be perfect to run a game server: while there are multiple options to run 64-bit distros on them, the default and recommended one is still 32-bit. Sometime even the proprietary driver for some device GPU is 32-bit only, though open source drivers are now in good shape but you may have to build it yourself from Mesa `main`. That's many reason causing armhf usage to still be strong. As a reflect of that, it looks like Debian arm64 usage report just went over Debian armhf this year, a few months ago.

**Comment by necessarily-equal** [comment]
I think armhf is still strong, and actually stronger than i386; but I also don't think we should mark either 32 bit platform as supported since it means we have one more burden before switching to wasm.

**Comment by illwieckz** [comment]
Speaking of Wasm, It looks like there is a 32-bit target:

```
$ llc --version | grep wasm
    wasm32     - WebAssembly 32-bit
    wasm64     - WebAssembly 64-bit
```

If a Wasm SDK doesn't have a 32-bit build it's not a big problem. For example the NaCl SDK only runs on i686/amd64 but can produce 32-bit armhf binaries. The big concern would be the virtual machine. For example Wasmtime only provides 64-bit builds (amd64, arm64…), but maybe it can be built for 32-bit of built by oneself?

**Comment by illwieckz** [comment]
Well, this is not a good sign:

```
$ git clone git@github.com:bytecodealliance/wasmtime.git
$ cd wasmtime/
$ git submodule update --init

$ cargo install bindgen-cli

$ sudo apt-get install gcc-arm-linux-gnueabihf

$ rustup target add arm-unknown-linux-gnueabihf

$ cargo build --target=arm-unknown-linux-gnueabihf

error: failed to run custom build command for `cranelift-codegen v0.91.0 (wasmtime/cranelift/codegen)`

Caused by:
  process didn't exit successfully: `wasmtime/target/debug/build/cranelift-codegen-b4a4b58dc2cfd7bb/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'error when identifying target: "no supported isa found for arch `arm`"', cranelift/codegen/build.rs:43:53
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...

$ sudo apt-get install gcc-i686-linux-gnu

$ rustup target add i686-unknown-linux-gnu

$ cargo build --target=i686-unknown-linux-gnu

error: unsupported architecture
  --> crates/runtime/src/trampolines.rs:58:9
   |
58 |         compile_error!("unsupported architecture");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
