### ISSUE TITLE
Alpha 51: Can't evolve from Adv Mara to Dragoon

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#1040]

**Comment by slipher** [comment]
Why is this a bug? I thought it was a gameplay decision at some point to only allow evolving to aliens with a strictly greater cost.

**Comment by illwieckz** [comment]
so perhaps the bug is the adv mara cost more than goon? :stuck_out_tongue_winking_eye: 

well, it makes sense to only evolve to  aliens with strictly greater cost, but on the evolution menu the goon is after the adv mara so it looks like a greater evolve form and it can be unintuitive to not be able to evolve to because of that if you don't see the evo price.

**Comment by slipher** [comment]
Adv. mara and goon both cost 6.

**Comment by DolceTriade** [comment]
In my trem days, you could evo from adv mara to goon. if this is intentional, I will close.

**Comment by Viech** [comment]
This is not *extremely* intentional. I know bots would crash the server by evolving back and forth indefinitely, and maybe this was a clutch fix. Personally I'm not against allowing this type of evolution. There is two greater things I'd like to do that could leave this as a byproduct: First, I want to get rid of "advanced" forms as they are merely a cheap way to have little more diversity, that introdcues a lot of code duplication. This could leave the alien costs strictly ordered. Then, I want evolution to be possible even when close to enemies, but locking you in place (maybe in some sort of cocoon) for a moment. This could be a reason to allow devolving, as you don't get the speed/maneuverability advantage immediately.
