### ISSUE TITLE
Germans can't use colors

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1131]
On German keyboards the circumflex opens the console.

![](https://upload.wikimedia.org/wikipedia/commons/3/36/KB_Germany.svg)

**Comment by illwieckz** [comment]
Key codes are now defined by their hardware position so they work the same whatever the layout, so the problem is that the circumflex key is physically the same as console key on german keyboard.

What do you think about harcoding this key the same way Shift+Escape is, but with a check box in preferences called "Quake console key" german players would be able to disable, and the customizable console key would be undefined by default, and german people would be able to set it to the key they prefer?

**Comment by illwieckz** [comment]
@slipher is it possible to detect that **hw:`** is equal to to **^** at runtime?

**Comment by slipher** [comment]
> @slipher is it possible to detect that hw:` is equal to to ^ at run time?
Yes, there is an SDL API for this.

There are two types of console key bindings, open-only and open/close. You make an open-only binding by using a regular key bind with the `toggleconsole` command. For open+close, you set `cl_consoleKeys`. 

My proposal is to add the console to the key binding menu, with special logic. It could `set cl_consoleKeys ""` while waiting for the key, and then `seta cl_consoleKeys <whatever>` after a key is pressed.

**Comment by illwieckz** [comment]
If we can detect the key collision, the idea of having the **`** key hardcoded as console key with ability to disable this one as the user disables it or the collision is detected looks not bad to me.

**Comment by Gireen** [comment]
Oh i didn't know its also possible to open the console with Shift+Escape.
With that its would be enough to make it possible to unbind hw:`

**Comment by slipher** [comment]
In the 0.52.0 branches, the console key can now be changed using the bind menu.
