### ISSUE TITLE
Can't download 0.51.1 assets via download-paks - md5sums is empty

### ISSUE THREAD

**Issue by dimhotepus** [Unvanquished/Unvanquished#1168]
Try to download assets for the latest version (0.51.1) from http://cdn.unvanquished.net/unvanquished_0.51.1/pkg/ via `./download-paks`:
> Empty file: /home/dimhotepus/github/Unvanquished/build/pkg/md5sums
> FAILED.

As i see [md5sums](http://cdn.unvanquished.net/unvanquished_0.51.1/pkg/md5sums) is empty:
> md5sums                                            09-Dec-2018 11:00                   0

Can you, please, update `md5sums` with md5 sums to allow flawless assets downloading?

**Comment by illwieckz** [comment]
Hi, its is known, see #1100. :smiley: 

Unfortunately we cannot modify the `md5sums` after release because it is part of the torrent and this server is also a webseed for the torrent. So we have to live with this mistake. We will make special efforts to not redo the mistake next time. :wink: 

If you use `download-paks` from latest master ([there](https://raw.githubusercontent.com/Unvanquished/Unvanquished/master/download-paks)), and install `aria2c`, it will download paks using bittorrent so you wouldn't have to mind the empty `md5sums` file.

**Comment by slipher** [comment]
>We will make special efforts to not redo the mistake next time.
The [release validation script](https://github.com/slipher/CheckRelease) I created recently checks that the md5sums are present and correct.
