### ISSUE TITLE
Opening build menu disable wallwalk when using non-toggled wallwalk

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1195]
I'm surprised to not find an already created issue for that since I'm sure I talk about it since a long time…

But when you use non-toggled wallwalk and open the build menu, the build menu intercept your keys so you fall.

**Comment by illwieckz** [comment]
I just thought about a workaround for this: make the granger always wallwalking when the build menu is opened. So the player would wallwalk before opening build menu by pressing the key, wallwalk while the build menu is opened because of the hack, then wallwalk after opening build menu because the player is pressing the key.

If we can detect if the player was wallwalking on the previous frame it would be better to avoid the view to be tilted on on flat surfaces, but even without that it would make non-toggled wallwalk usable.

**Comment by slipher** [comment]
Maybe we could have menus that intercept only the mouse and not keys. I've often wished to be able to walk around while opening a menu.

**Comment by slipher** [comment]
Although, the evolve and build menus really ought to allow you to select things with the number keys, so maybe not.

**Comment by illwieckz** [comment]
I don't know how to tell server to wallwalk from the client code. Commands like `+movedown`, `+forward` or even `+attack` exist but do not work when not called from a key bind.

**Comment by illwieckz** [comment]
Note that we may want to apply such hack on all menus (like the main menu).

I'm not sure we can do it on console but I don't care, we must give true chat window to player instead of hijacking the console.

**Comment by slipher** [comment]
I thought of a possible design for allowing binds to be used while in a menu. Instead of having the `KEYCATCH_UI` flag (which is set when a menu is open and disables all binds), have the cgame return a bool in reply to `CGameKeyEventMsg` indicating whether the key event was consumed by the cgame. Then key binds will be processed only if this bool is false.

This would allow a circlemenu to consume only number keys (and possibly a handful of others like tab and enter that librocket enables by default for navigation). So as long as your wallwalk key isn't one of those, you could use it while the circlemenu is open. 

For options menus I'd probably have it just consume all keys. It's not that useful to walk around while a full-screen menu is open; it would just seem like a bug.

In librocket there is already a notion of stopping event propagation, and `Context::ProcessKeyDown` returns whether the event was consumed. So there won't be much additional plumbing.

@bmorel @Gireen may be interested

**Comment by Gireen** [comment]
So that means if a key event happens and a menu is open it triggers a lua event and it can then be decided if the key catched or not?
That would then also allow to process keys by librocket and the game?

With that case it would also be possible to add scrolling to the scoreboard.

Could that be also extended to mouse movement, that librocket can react on changes in the view without catching the mouse?

**Comment by slipher** [comment]
> So that means if a key event happens and a menu is open it triggers a lua event and it can then be decided if the key catched or not?
> That would then also allow to process keys by librocket and the game?

Yes.

> Could that be also extended to mouse movement, that librocket can react on changes in the view without catching the mouse?

Things can be done the same way for mouse clicks and mouse wheel scrolling. But for mouse movements, it is not possible - librocket does not return a bool indicating whether it was consumed.

**Comment by slipher** [comment]
Fixed by #2900.
