### ISSUE TITLE
RmlUi issues

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#1200]
Global Issue tracker for RMLUI issues
- [x] ColorInput doesn't work
- [x] In game focus is borked
- [x] Fix deprecated decorator syntax aka broken checkbox and others
- [x] Rocket progress bar needs to be refactored
- [x] Human hud has color issue (was probably using [foreground-color bug](https://github.com/Unvanquished/libRocket/issues/7) as a feature)
- [x] Cursor scaling was lost in translation
- [x] UI scaling was lost in translation
- [x] Add support for transforms.
- [x] Circle menus are broken
- [x] human health blinks when it goes down
- [x] Backup font face
- [x] Cursor only visible over document

**Comment by illwieckz** [comment]
The game suddenly quit the game and returned to the main menu.
There was that in log:

```
Warn: RE_AddRefEntityToScene: bad reType 1048033888
```

**Comment by slipher** [comment]
I rebased everything locally to check if my [circlemenu rewrite](https://github.com/UnvanquishedAssets/unvanquished_src.dpkdir/pull/40) (just the beacon menu so far) will still work. It was mostly OK after doing the required mechanical substitutions. I did find that the buttons get darker, rather than lighter, when you hover over them (this affects the other circlemenus too), which looks weird. The other circlemenus look a lot better, by the way - I can actually tell which buildable I am going to build in the build menu!

Other issues I noticed:
- Console and chat messages don't appear
- A few `Syntax error parsing property declaration` warnings

**Comment by slipher** [comment]
Pushed a new version of the code to the `rmlui3/sync` branch (in this repository and unvanquished_src.dpkdir).

Fixed 3 of the open issues in the OP (UI scaling, circle menus are broken, human health blinks). The other one open there (implement transforms) is not important to fix as we don't use it. I adding a warning log that will trigger if someone tries to use it.
Added 2 more issues that haven't been solved yet:
- "Backup font face" feature was lost. See if this is needed; maybe it can be done in CSS.
- The custom cursor disappears when it goes outside the bounds of the open menus (e.g. with the select team dialog).

Note that we are using a pretty old version of RmlUI now, from March 2020. I don't want to update right away because they completely changed the source layout again.

**Comment by necessarily-equal** [comment]
Removed from milestone because everything but «  Add support for transforms. » has been ticked, and we don't need that for 0.53

**Comment by DolceTriade** [comment]
Everything has been checked off, so closing this.
