### ISSUE TITLE
Bots need a delay before spawning in

### ISSUE THREAD

**Issue by Stooberton** [Unvanquished/Unvanquished#1236]
Currently, bots spawn in and start playing as soon as the map finishes loading which is significantly faster than player load times. This is detrimental due to bots dying/killing and even ending up inside bases before any player has had a chance to spawn.

**Comment by illwieckz** [comment]
Thanks for the report. Yes, I confirm this.

There is a mechanism which is worked on to pause the server until real people join (see #1234), but this will not help that much on that side because bots we will still be able to join the game and start wrecking your base before you map is fully loaded (and even downloaded if you don't have it yet).

There is a countdown that is configurable but it can be frustrating to some players.

One possible stateless and non-so-much-intrusive implementation would be to prevent bots to spawn (I mean spawning from telenode/eggpods, even if successfully loaded up and joined team) if there is no one real player connected and alive (in a team and spawned). That would prevent spectating bots, which may have useful debug uses, so it behaviour be enabled by a cvar that would be on by default.

**Comment by slipher** [comment]
Server owners can already configure this by setting `g_doWarmup` and `g_warmup`.

The bot pause mechanism will not change anything because it is based on the presence of *connected* players.

**Comment by illwieckz** [comment]
Yep I was talking about warmup when I said:

> There is a countdown that is configurable but it can be frustrating to some players.

**Comment by Gireen** [comment]
yeah numConnectedPlayers does also count connecting players ... 
but that can be changed (do we need a numRearllyConnectedPlayers? 🙃)  

bots could also play at the beginning more passively, like using the camper behavior.

**Comment by bmorel** [comment]
> Server owners can already configure this by setting g_doWarmup and g_warmup.

This does not work AFAIK, so I'd change the status of this issue to T-Bug instead of feature request.
