### ISSUE TITLE
Add default configuration to run local public servers

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#1268]
It would be nice if the content of dist/configs would be used by default if running a server

**Comment by illwieckz** [comment]
How to embed such files, can we ship a map rotation file in a dpk file?

**Comment by Pretuer** [comment]
> It would be nice if the content of dist/configs would be used by default if running a server

This is a great idea, I am planning to make some pro-game tournaments I'd appreciate if this was in to simply the proceedure to make a game and allow people to join

**Comment by Gireen** [comment]
@illwieckz a maprotation in dpk files rearly works. 😯
but it cant be overwritten by a local create maprotation.cfg. that shouldn't happen i think.

Is viable to extract files from a dpk on start like it happens with the vm?

**Comment by illwieckz** [comment]
We may do that but I have mixed feelings about this. I remember how it was a mess with GtkRadiant package installation, where gamepacks installed required assets in the homepath: either you don't overwrite and then something the user never modified (so does not know it exists and where) starts to fail with updates, either you overwrite and the user loses its edits.

Maybe we can do a `defaultrotation.cfg` file name or something like that that would be loaded from dpk if `maprotation.cfg` is not there, so this file would only be loaded when the user has not made a custom one, making sure it is always up to date (since it would be shipped with the game), while users who would use a custom one would already know how to edit their custom file to fit future releases.

**Comment by Gireen** [comment]
that might be even easier. a defaultmaprotation.cfg witch contains a defaultRotation1 and is always loaded. and if the initial rotation doesn't work it can act also as fallback.
