### ISSUE TITLE
Turrets fire through doors

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1305]
Rockets and bullets from turrets can go through door, as seen in following screenshot (only rocket).

Easy to reproduce on perseus: as a human, build a turret in the 3-door room next to human base (close enough to door, especially for mgturret), then switch to alien, and move in range of (so that they can spot you) without opening the door.
You will be welcome by ghost rockets and bullets, which go through walls but hurt you.

I think there is 2 bugs here:

* turrets should probably not spot aliens "hidden" behind doors
* turret's ammo should collide against doors

I tried with acid tubes and hives as well, they don't have that behavior. I tried with trapper, but could not place it close enough and facing door to ensure, and didn't tried with the (useless) spiker, so I believe this is a turret-specific thing.
![ghost_rocket](https://user-images.githubusercontent.com/1316300/106392104-aa931980-63f0-11eb-98a9-457dbf88c277.png)

**Comment by cu-kai** [comment]
For reference, this is directly related to https://github.com/UnvanquishedAssets/map-perseus_src.dpkdir/issues/4

There may be some other bug going on with the engine, because according to NetRadiant, the entire door should be nonsolid, but in my ingame experiment, only the middle part was nonsolid.

**Comment by illwieckz** [comment]
> There may be some other bug going on with the engine, because according to NetRadiant, the entire door should be nonsolid, but in my ingame experiment, only the middle part was nonsolid.

What I've heard is that on a brush, you can have more than one side (obvious) and each side can have a different texture (obvious), but that only one side decides if the whole brush is solid or not (less obvious), so if the side-that-decides-for-the-whole is like, a solid caulk, and the unseen external side of the door which is actually caulked is this one, then it may explain why the whole door was not non-solid despite having non-solid surfaces. This computation is done in q3map2 if I'm right. This is like “I have heard something like that”, it may be good to check, but that makes sense and may explain what happened there.

Anyway the surfaces were modified to use solid variant of the texture itself, and then it looks fixed in game. I was not able to shoot through them with a pulse rifle, neither build a medistation under the glass of the other affected doors.

**Comment by illwieckz** [comment]
Note: if you notice this bug on another map, please open a new issue on the related map issue tracker.
