### ISSUE TITLE
Whilst you heal you run faster 

### ISSUE THREAD

**Issue by Pretuer** [Unvanquished/Unvanquished#1339]
not sure if anyone has  noticed: whilst you heal you run faster (bug or feature (could be in lore that humans have a "speed" drug that helps them to heal wounds) in turn the drug makes you run a little faster 

this tool could be exploited to make a drug dedicated in buffing humans

**Comment by Calinou** [comment]
Does this only occur when using the medkit, or does this also occur after walking on a healing pad? If it's the former, this may be intended.

**Comment by bmorel** [comment]
I can not reproduce this bug.
Testing procedure: `/devmap thunder` because it have big corridors. Move at entrance of one of those, build an acid tube, take damages, go to the other side. Enable `cg_drawSpeed`, sprint straight. Max speed is 383. Use the medkit: no change in max speed.
Same applies without sprinting, in normal jogging, except speed is 319.

**Comment by necessarily-equal** [comment]
I also never noticed this
