### ISSUE TITLE
g_disabledEquipment and g_disabledClasses needs improvements

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1361]
Those variables needs several improvements:

* they should be processed when set in the middle of a game
* they should have user interface allowing to edit them
* they should detect errors when set (it is unclear for now if they work at all, from my point of view, but can't be sure since they won't complain when you assign erroneous strings to them)
* they should affect bots

And, to be honest, I'd better see them replaced with something more sensible, which should be discussed.
For example, since there are already equivalents for bots ( `g_bot_${EQUIPMENT}.integer` ), maybe those things could be merged, more generically.
I think have a bitfield for each upgrade, weapon and class so that one could allow or prevent either bots, humans or both to use it would be better. An even better implementation might be to allow specifying the bot skill level at which they should be authorized to buy it.

In any case, I'm almost certain those vars are heavily bugged, if working at all.

**Comment by Gireen** [comment]
These variables date back to tremulous times. For mappers or serverowners to disable for example jetpacks for specific maps.
What do you want to use them for?

> they should affect bots

they do

> In any case, I'm almost certain those vars are heavily bugged, if working at all.

from looking at the code they look like they should work normal. 

Its more of an obscure functionality with is not used anywhere. I think the names are the ones used by the config files

**Comment by necessarily-equal** [comment]
I'm working on a fix. One thing I'm wondering is, if this is set by the map, do we want to allow people to override it? Do we want it to have two variables instead? Where the second would "force disable" the upgrade? Do we want to add some UI to it?

**Comment by necessarily-equal** [comment]
So first of all, this is one of those "this thing is not so great" issue that are impossible to close, because they talk about so many things at once. Should this be closed once this has improved a bit? Should be this closed only when we implement an UI for it? Should this be fixed once the cvars have been transformed into many cvars?

But let's provide an update on this.

Since https://github.com/Unvanquished/Unvanquished/pull/1503, the following are true:
* [x] they should be processed when set in the middle of a game
* [ ] they should have user interface allowing to edit them
* [x] they should detect errors when set (it is unclear for now if they work at all, from my point of view, but can't be sure since they won't complain when you assign erroneous strings to them)
* [x] they should affect bots

The 4th is actually true: bots *can't* buy those weapons. But they will try to, and keep trying to, and keep trying to endlessly until the items are locked again or they loose the money for some reason. This should be tracked in https://github.com/Unvanquished/Unvanquished/issues/1586 IMO.

So it seems the only thing left is an UI for it, I'm personally not interested in it, especially since it would be really hard to get correct, as the map can override those defaults. I'm closing this, but if you think an UI for this is worth it, please open an issue dedicated for that, as it would otherwise be really hard to understand from reading this issue alone, that the only thing left here is an UI request. If I missed something else, by chance, please open an issue for that too.
