### ISSUE TITLE
[0.52 RC] Deleted shaders and delta paks

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#1377]
If a file in a pak repository exists in revision A but not revision B, and you have a file that exists in version A but not version B, and you make a delta DPK from A to B, the result is not correct because there is no way to delete a file. This becomes a problem with resources that are loaded automatically without being explicitly referenced, such as q3shaders and emoticons. 

The specific case I encountered with the 0.52 RC is the shader `models/weapons/rifle/smg`. In the 0.51 package it is defined in the file `scripts/smg.shader`, later deleted. In the 0.52 package it is defined in `scripts/rifle.shader`. I get these warnings from the old definition: 
```
^3Warn: deprecated idTech4 standalone stage 'diffuseMap' in shader 'models/weapons/rifle/smg', better move this line and pack related textures within one single curly bracket stage pair
^3Warn: deprecated idTech4 standalone stage 'normalMap' in shader 'models/weapons/rifle/smg', better move this line and pack related textures within one single curly bracket stage pair
^3Warn: deprecated idTech4 standalone stage 'specularMap' in shader 'models/weapons/rifle/smg', better move this line and pack related textures within one single curly bracket stage pair
```

I believe the definitions are lazily parsed when a named shader is requested, so the fact that I'm seeing this means the old one is actually being used.

I don't know how many other deleted files might be affected. @illwieckz Do you know an easy way to get a list of all files in pak repositories deleted between 0.51 and 0.52?

**Comment by illwieckz** [comment]
Yes, we already faced a similar problem at pre 0.51 time, for example if 0.50 package provided `textures/something/something.png` and 0.50+1 provided `textures/something/something.crn`, the 0.50+ game would have loaded `textures/something/something.png`, and this one may have not only been the lossless version of the other, but an obsolete one that was modified since…

Before thinking about the technical means to list deleted files between packages, I thought about a simple file, like `DELETED` that would simply list paths to not lookup in the packages listed in DEPS. This is a simple design, but I was worried about implementing it in both Dæmon and NetRadiant, so I just left this idea for future generations™ at the time.

About listing deleted files, listing the deleted source files is easy (just the delta between to `git ls-files`) but because one source file may produce more than one built files (example: `.map` produces one `.bsp` and an unpredictable amount of `lm_*` lightmaps), unless I miss something, it would not be easily possible to list the deleted files without having some build log of the previous package.

**Comment by illwieckz** [comment]
Well for a `.shader` file that is just copied, comparing `git ls-files` output can be enough to know it's deleted, also git may somewhat delete the rename and we may rely on that. With the `.bsp` example I'm just saying detecting deleted files for all formats can be tricky. Most of the time it would not be complicated (`copy` rule  or conversion rule with 1 source and 1 target), but sometime, it would be a complex problem.

**Comment by illwieckz** [comment]
For the specific shader case, we may not iterate the vfs alphabetically, but alphabetically from recent package to older package, but that would defeat a bit the idea of a simple vfs without knowledge of the package dependencies once loaded…

**Comment by illwieckz** [comment]
For the immediate need, we can build non-delta DPK for 0.52 and see what was deleted.

**Comment by slipher** [comment]
For the final release we did not use delta paks.

**Comment by illwieckz** [comment]
See https://github.com/DaemonEngine/Daemon/pull/521 for an engine and DPK feature to ignore deleted files from deps of delta paks.
