### ISSUE TITLE
Custom FOV is reset when running `vid_restart` or using the "Apply now" button

### ISSUE THREAD

**Issue by Calinou** [Unvanquished/Unvanquished#1382]
When using a custom FOV (tested with `cg_fov_human 106.26` playing as a human), applying video settings will reset to the default FOV. It's not possible to change this FOV while playing either (or not reliably at least), so it can be quite annoying.

Using `/reconnect` while playing on the server doesn't seem to solve this, although the server switching to the next map will solve this.

**Comment by illwieckz** [comment]
As far as I know, it's not expected to change the FOV and is part of the gameplay. For example the dretch is expected to have wider FOV than humans and this is part of it's ability (like wallwalking) and its character.

**Comment by Calinou** [comment]
Until https://github.com/Unvanquished/Unvanquished/issues/1383 is implemented, removing adjustable FOV would be a mistake since it would give headaches for pretty much any widescreen player :slightly_frowning_face:

**Comment by illwieckz** [comment]
That's why I said I have no opinion on this. Assuming a year 2000 4:3 screen would be wrong indeed, but because it looks like that FOV thing was initially part of the character design, we would have to decide to go against that design before merging any simple commit unlocking the FOV, the problem has non-technical aspects. 

That said, may be we can implement a fov factor… that would keep the various fov difference among characters.

**Comment by slipher** [comment]
If FOVs are not intended to be customizable then why are they cvars?

**Comment by cu-kai** [comment]
I play with a high FOV for all classes and do not recall any issues with FOV being reset on vid_restart. I cannot reproduce this on a current build of daemon on the map testing server.

**Comment by slipher** [comment]
I can't reproduce it getting reset either. Also, the FOV can be changed instantaneously.
