### ISSUE TITLE
Some crash? on Manjaro reported by Tchey on gamingonlinux.com

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#1404]
Reported by Tchey [here on gamingonlinux.com](https://www.gamingonlinux.com/2021/05/free-first-person-strategy-shooter-unvanquished-releases-version-052-beta/comment_id=203440):

>  Hm... Installed, and then when i go to the directory, open a terminal to launch, i see the launcher a couple seconds and it goes boom.
> If someone knows something... Thanks.

```
[tchey@ordimanj Unvanquished]$ ./updater
Git version: v0.1.0
4 stored settings:
 - "settings/commandLineParameters" = "%command%"
 - "settings/currentVersion" = "0.52.0"
 - "settings/installFinished" = "true"
 - "settings/installPath" = "/home/tchey/Jeux/Unvanquished"
Testing exception handling...
Exception handling works
QFontDatabase: Cannot find font directory /qt/lib/fonts.
Note that Qt no longer ships fonts. Deploy some (from https://dejavu-fonts.github.io/ for example) or switch to fontconfig.
CurrentVersionFetcher: fetched versions: updater = "v0.1.0" game = "0.52.0"
Previously-installed game version: "0.52.0"
Starting game with command line: "\"/home/tchey/Jeux/Unvanquished/daemon\""
Unvanquished 0.52 Linux x86_64 May 13 2021
cmdline:
[FS] Lib path: /home/tchey/Jeux/Unvanquished 
[FS] Home path: /home/tchey/.local/share/unvanquished 
[FS] Pak search path: /home/tchey/Jeux/Unvanquished/pkg 
[FS] Pak search path: /home/tchey/.local/share/unvanquished/pkg 
Warn: Could not connect to existing instance: Connection refused 
Starting crash logging server 
[FS] Loading pak '/home/tchey/Jeux/Unvanquished/pkg/unvanquished_0.52.0.dpk'.. ]
[FS] Loading pak '/home/tchey/Jeux/Unvanquished/pkg/tex-common_2.2.dpk'... 
[FS] Loading pak '/home/tchey/Jeux/Unvanquished/pkg/res-players_0.52.dpk'... 
[FS] Loading pak '/home/tchey/Jeux/Unvanquished/pkg/res-legacy_0.52.dpk'... 
[FS] Loading pak '/home/tchey/Jeux/Unvanquished/pkg/res-weapons_0.52.dpk'... 
[FS] Loading pak '/home/tchey/Jeux/Unvanquished/pkg/res-buildables_0.52.dpk'.. ]
[FS] Loading pak '/home/tchey/Jeux/Unvanquished/pkg/res-voices_0.52.dpk'... 
[FS] Loading pak '/home/tchey/Jeux/Unvanquished/pkg/res-soundtrack_0.52.dpk'.. ]
execing 'default.cfg' 
execing 'presets/input/wasd.cfg' 
Warn: Couldn't read conhistory: No such file or directory
```

> Linux Manjaro (Arch) 64bits Xfce
> Intel Core i5 4590 (4 x 3,3 GHz)
> GeForce GTX 1060 @ 6 Go
> Nvidia Drivers
> 16 Go DIMM DDR3 PC12800
> SSD Crucial 480Go
> BENQ GL2460 16/9 24" 1920x1080

**Comment by illwieckz** [comment]
The updater seems to work and chainload properly the game, I don't see anything related to a crash in the log. and the Warn are harmless.

**Comment by slipher** [comment]
The significant part is `Warn: Could not connect to existing instance: Connection refused`

**Comment by illwieckz** [comment]
Maybe do:

```
rm ~/.local/share/unvanquished/lock`
```

**Comment by mboerwinkle** [comment]
Hello,
 I get what appears to be a similar crash (maybe the same?) on Arch. I was able to reproduce it with a debug build; I've included inline, below, some GDB interaction.
 If I'm understanding correctly, it looks like it is caused because (1.) I haven't set a language, (2.) I have a locale language, but (3.) I don't have a locale country.
 Please let me know if there is anything else I can provide.
Thanks for your help,
Martin
#####
[test@MartinPC debug]$ gdb ./daemon
GNU gdb (GDB) 10.1
<Removed Text>
Reading symbols from ./daemon...
(gdb) run
Starting program: /home/test/Downloads/unvanquished/debug/daemon 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Unvanquished 0.52 Linux x86_64 May 14 2021
cmdline:
[New Thread 0x7ffff6377640 (LWP 570085)]
[FS] Lib path: /home/test/Downloads/unvanquished/debug 
[FS] Home path: /home/test/.local/share/unvanquished 
[FS] Pak search path: /home/test/Downloads/unvanquished/debug/pkg 
[FS] Pak search path: /home/test/.local/share/unvanquished/pkg 
][New Thread 0x7ffff5841640 (LWP 570086)]
[FS] Loading pak '/home/test/Downloads/unvanquished/debug/pkg/unvanquished_0.52.0.dpk'... 
[FS] Loading pak '/home/test/Downloads/unvanquished/debug/pkg/tex-common_2.2.dpk'... 
[FS] Loading pak '/home/test/Downloads/unvanquished/debug/pkg/res-players_0.52.dpk'... 
[FS] Loading pak '/home/test/Downloads/unvanquished/debug/pkg/res-legacy_0.52.dpk'... 
[FS] Loading pak '/home/test/Downloads/unvanquished/debug/pkg/res-weapons_0.52.dpk'... 
[FS] Loading pak '/home/test/Downloads/unvanquished/debug/pkg/res-buildables_0.52.dpk'... 
[FS] Loading pak '/home/test/Downloads/unvanquished/debug/pkg/res-voices_0.52.dpk'... 
[FS] Loading pak '/home/test/Downloads/unvanquished/debug/pkg/res-soundtrack_0.52.dpk'... 
execing 'default.cfg' 
execing 'presets/input/wasd.cfg' 
Warn: Couldn't read conhistory: No such file or directory 
]
Thread 1 "daemon" received signal SIGSEGV, Segmentation fault.
0x00005555555a701a in Trans_LoadDefaultLanguage ()
    at /home/test/Downloads/unvanquished/daemon/src/engine/qcommon/translation.cpp:290
290				Cvar_Set( "language", va( "%s%s%s", locale->lang,
(gdb) bt 
#0  0x00005555555a701a in Trans_LoadDefaultLanguage ()
    at /home/test/Downloads/unvanquished/daemon/src/engine/qcommon/translation.cpp:290
#1  0x0000555555585a17 in Com_Init ()
    at /home/test/Downloads/unvanquished/daemon/src/engine/qcommon/common.cpp:637
#2  0x0000555555619752 in Application::ClientApplication::Initialize (
    this=<optimized out>, uri=...)
    at /home/test/Downloads/unvanquished/daemon/src/engine/client/ClientApplication.cpp:74
#3  0x00005555557460b9 in Application::Initialize (uri=...)
    at /home/test/Downloads/unvanquished/daemon/src/engine/framework/Application.cpp:69
#4  0x000055555576e824 in Sys::Init (argc=1, argv=0x7fffffffe468)
    at /usr/include/c++/10.2.0/bits/basic_string.h:901
#5  0x000055555576e996 in main (argc=<optimized out>, argv=<optimized out>)
    at /home/test/Downloads/unvanquished/daemon/src/engine/framework/System.cpp:679
(gdb) print locale->lang
$1 = (FL_Lang) 0x555556588210 "c"
(gdb) print language->string[0]
$2 = 0 '\000'
(gdb) print locale->country[0]
Cannot access memory at address 0x0
(gdb) print locale->country
$3 = (FL_Country) 0x0
(gdb)

**Comment by slipher** [comment]
Thanks @mboerwinkle for the detailed information - opened https://github.com/DaemonEngine/Daemon/pull/469.

Nothing in the log in the OP indicates that this is the same issue, but it's not unlikely since this was a new regression compared to the last release.

**Comment by necessarily-equal** [comment]
Can you test this patch?
```diff
diff --git a/src/engine/qcommon/translation.cpp b/src/engine/qcommon/translation.cpp
index 68104b49..1f8b3fdc 100644
@@ -288,7 +288,7 @@ void Trans_LoadDefaultLanguage()
                else
                {
                        Cvar_Set( "language", va( "%s%s%s", locale->lang,
-                                                 locale->country[0] ? "_" : "",
+                                                 locale->country && locale->country[0] ? "_" : "",
                                                  locale->country ) );
                }
 
```

**Comment by Jeux1d100** [comment]
Hello,

I’m the OP guy, thanks for posting here for me.

My system is in French. I tried to do 
export LC_ALL=C
then
./daemon or ./updater

same result

i tried to do
rm ~/.local/share/unvanquished/lock
then 
./updater

same result

**Comment by slipher** [comment]
> but then i tried to do
LC_ALL="fr_FR.utf8"
then
./updater
>
> and... i’m in game menu now.

Thanks, so we know it is indeed the same issue that @mboerwinkle reported.
