### ISSUE TITLE
BotActionFlee is broken

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1577]
steps to reproduce:
* make a BT that contains `action flee` (for example replacing the `action heal` in the `default.bt`)
* `/bot add * aliens 5 my_bt_name`
* notice how the bot will rush to the overmind, and will never consider this action done: it's stuck.

how to fix:
* copy or rather reuse code from BotActionMoveTo, so that the action succeeds if the bot is "close enough" from the buildable.

**Comment by necessarily-equal** [comment]
workaround:
`action moveTo( E_A_OVERMIND )`

**Comment by bmorel** [comment]
According to code, the problem is from the "standard" radius 70 which is used in almost all conditions.
When you do BotMoveTo( overmind ), the radius is guessed by `BotGetGoalRadius()`, which is either `radius( self ) + radius( goal )` or `self.maxs[0] + target.maxs[0]`.

Using a magic number is obviously the wrong thing to do, in many, many places, especially when one takes the bigger pair of entities, that is, tyrant (32) and overmind (45), which ends up in either 77 or ~109.
In that code reading, it's also rather obvious that the "maxs + maxs" cases are wrong, so here, there are 2 bugs:

* using added half-sizes instead of actual radiuses
* using hard-coded magic value 70

**Comment by bmorel** [comment]
There another thing to keep in mind: what is the point of BotActionFlee anyway? Is that meant to be a faster runaway than BotActionHeal?
Should BotActionHeal allow for opportunistic attacks, unlike BotActionFlee?

**Comment by necessarily-equal** [comment]
You can find a partial "BotActionFlee" (that I did call BotActionGetInSafety to avoid name collision) [here](https://github.com/necessarily-equal/Unvanquished/commit/db58395dc913c2dab0a5261f3c0569654d5fbef2). It's implemented for a special case where one has no base, and unfinished.

Things I would like to do so that it is a proper jugg flee function:
* Add navmesh distances checks to ensure that the point we want to reach at a ghost distance of 100 is at a walking distance of max ~150
* Add the fast flee support
* Add traces in the fast flee to only jump if it is useful
* Add the enemy equipment to the danger weighting function
* Add opportunistic biting

Note that my objective is to ensure an actually scary jugg — not all player may want really scary regular bots :P

**Comment by necessarily-equal** [comment]
Oh, and to explain how this works: this essentially looks at how many enemies there are "in each direction" and walks in the least risky direction.

**Comment by bmorel** [comment]
> Add the fast flee support

Should be pretty easy to do the hackish way if you base on current code: add a flag to botmind "fastMove" to replace the team check in BotMoveToGoal(), have the actions `flee` and `heal` to set it, and clear it on success and failure (so, it's set as long as action is running) and it will magically work.
Note that this could actually be used for more actions, like the rush or whatnot. Such flag could even be set by a BT action I guess.

> Add traces in the fast flee to only jump if it is useful

You meant pounce. That's a good point.
I tried to implement aiming at the next corner, but that hardly work (in many situations, the goon does not aim high enough to actually pounce. I need to check if that globally slows them down or not, but it's clearly sub-optimal).
One should probably make bots (especially goons and tyrants) to jump instead of pounce/charge when distance is too reduced (except if bot should be prevented to jump because of stamina handling), that would augment their speed while making them be more precise (which is currently a big issue). Maybe even not jump if distance is *really* too low... (thinking about the mara problem here)
If only there was a jumpAt() function, that would be perfect...

> Add opportunistic biting

One naïve way to implement this would be to trigger an attack in BotAvoidObstacles() if the trace shows the obstacle is an enemy entity, while still trying to steer/avoid it.
That would work for aliens at least, since they're all about melee attacks, and would have limited effect for humans too.
Note that it would be incompatible for goons with the actual implementation of the fast flee (pounce preparation and charging of tyrant prevents attacking), but that's hardly surprising since I've always considered the fast flee code hackish for aliens (yet, it's quite efficient in various cases).
Heh, this is something that I should be able to do easily in my current obstacle avoidance code... need to think more about it.

> Note that my objective is to ensure an actually scary jugg — not all player may want really scary regular bots :P

Note that I consider only SK9 should be scary to *any* player, and that it's (still) not scary to me, just quite difficult and dangerous. Better handling of fleeing might help on that issue :D
As usual, enabling or affecting efficiency of things depending on bot's skill is the way to go to ensure funnier experience to everyone, depending on the AI settings.
On this, I think that at some point, when there will be enough things implemented, some re-calibration should be done (after there's a tutorial to teach players how to play, though).

> Oh, and to explain how this works: this essentially looks at how many enemies there are "in each direction" and walks in the least risky direction.

Yes, that's something I think it should do instead of reaching OM/RC. This way, even in normal BTs, bots should be able to simply flee and then go heal when the coward is safe. This would prevent bots traversing enemy bases to go heal, which is a pretty stupid behavior.

**Comment by bmorel** [comment]
>  I did call it BotActionGetInSafety to avoid name collision.

That's something I also do now, when I rewrite pieces of code: I keep old code around, add the new one with a different function signature (sometimes name if that helps) in a 1st commit, and in a 2nd commit, I remove previous implementation and enable the improved one. That helps with diffs (and thus rebases/merges), since diff does not handle context.

**Comment by bmorel** [comment]
Nowadays, I think the "flee", "heal", "fight", "roam", and "rush" actions should be utterly removed. There's a lot of thinking behind this, but in a nutshell, actions should be about defining goals, either long term or short term ones, and short term ones should stack.
Ask if you want to have more of my thinking written here (but keep in mind that, while doing it here it won't be lost, I'll also spend time I could spend to implement it).

**Comment by necessarily-equal** [comment]
Looks like it is fixed.
