### ISSUE TITLE
On low health/ammo, unpowered medistation and/or armory are blinking

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#1580]
Steps to reproduce:
* destroy reactor
* waste ammo
* `/give health -80`
* notice how things are blinking while they shouldn't

**Comment by bmorel** [comment]
To explain more what I suppose is the issue here:

* the cross icon on medistation appears (and blinks, both on minimap in normal view) on the unpowered medistation
* the bullet icon to warn about resupply appears on the unpowered armory

While it's normal to have those icons, of which only the cross blinks, they should probably not appear on unpowered buildings since it can give wrong indications to players, for example if some  are disabled because of a lack of BPs.

**Comment by illwieckz** [comment]
I wonder if that's related to alien bots trying to heal on unpowered booster, and if #1784 will also fix that.
