### ISSUE TITLE
locked buildings can still be built after momentum loss

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1614]
It is possible to place buildings after they have been locked by a momentum loss.

To reproduce:

* /devmap plat23
* /team a
* /give momentum
* as a granger (or adv granger), select hive
* /give mometum -2000
* try to place the hive. This will work, and I think it should not.

**Comment by illwieckz** [comment]
I don't believe it's a bad idea to allow the player to take all the time he needs to place a buildable he actually managed to select before momentum was lost. It's like, you got it, now place it. I always considered this as a feature, the same way you can use your bsuit after momentum is lost.

Being suddenly forbidden to place a buildable you had enough momentum for to select and place only because you took extra time to carefully place it (or the geometry made it not possible and you had to move a bit) may be felt very frustrating and stressful (we may not need to add more stress to the game).

**Comment by bmorel** [comment]
Agree. But it feels weird to have the text saying you can't why still being able to :)

As for the precision and geometry, this is a different issue, but in a nutshell, I think the game should help a bit the player instead of being as strict as it currently is, especially for alien structures. Being able to adjust the distance where the building will be placed to would also help immensely. Still: different issue.

**Comment by bmorel** [comment]
So, in the end, should this ticket be closed, or should it require some sort of documentation to describe this behavior? (I'm fine with all solutions)

**Comment by Gireen** [comment]
If it cant be abused or frustrates players its not a bug. 
Not sure if there is any need to document it. Players should normally not be able to notice this anyway.

**Comment by bmorel** [comment]
Alright, let's close it then.
