### ISSUE TITLE
proper handling of barricade shrinking for bots

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#1863]
Bots don't really know how to jump over barricades.
If they see a barricade and are aliens, they jump. If they're not fast fleeing.
Barricades have a constant indicating their shrink size, it should be used by obstacle handling.
Or better, navmesh for aliens should be updated so that they understand the barricade's actual size. Humans should not, because they're not meant to know about it yet.
Not an easy topic, despite how it looks.

**Comment by necessarily-equal** [comment]
So there are several issues described here:

1. Fast fleeing may handle barricades wrong, as bots don't attempt to jump.
2. Barricades don't affect navmesh "like they should". I think the current handling is correct: obstacles are just never created. I think this is correct for aliens because either the barricade is powered and the alien can get through, or it is unpowered and the barricade's wall is lowered anyway and the alien can get through. I also think this is correct for humans because (as you said) they are not supposed to know there is a barricade here.
3. « navmesh for aliens should be updated so that they understand the barricade's actual size » I'm afraid if you mean something such as "give some information that it's like if the the roof was lower here", this is currently very out of reach and probably not worth working on at the moment.

I think 2. is fixed and 3. is currently a non-goal. With a bit of testing, it seems 1. is a problem only for goons in an upward slope like on parpax' staircaises. it's not a huge deal either I guess, since bots will heal on the obstacle instead by accident :P

I may backport your jump commit if I can find a bug fixed by it or if it doesn't conflict with what I have in mind for https://github.com/Unvanquished/Unvanquished/issues/2263. But for now, I don't think there is a problem that we have to fix here so I'll remove this from the 0.54 milestone.

**Comment by bmorel** [comment]
>  I think the current handling is correct: obstacles are just never created. 

You are wrong. Except if someone touched this in the, say, 6 past months, then an obstacle is added, and alien bots just ignore it if it's a barricade. When it's a barricade, BotShouldJump basically returns true, even if the bot can not jumps over it, which can happen when said barricade is at the top of a ramp (happens fairly often in plat23).

>  I'm afraid if you mean something such as 

No, I really meant update navmeshes when barricade shrinks or grows, which would allow for human bots to follow a fleeing alien through there, like what humans do sometimes.

**Comment by bmorel** [comment]
For the reference, I think the use of navmesh changes to handle buildings is a huge error. A better workaround would be to increase travel cost of tiles occupied by buildings instead, to make bots naturally find their path around or above them. This would allow bots to be stuck on buildings when there is no other passage to reach a place than go through the building, but then, if building is not a friendly one, they should shoot at it instead, and if it's a friendly one, they would be stuck anyway. This would notably fix #2361 in a much cleaner way than the currently implemented hack.
