### ISSUE TITLE
improve the oxygen bar

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2035]
As of 0.53, the oxygen bar can be improved in several areas, not counting the few little bugs:

* it should blink in red when drowning instead of disappearing (or at least show it's empty)
* it does not appear for spectator

There are also 2 bugs:

* it shows when other players are underwater, fixed by #2034 
* it does not shows when one spawns underwater

I still thing this is a nice improvement compared to 0.52, if #2034 can be merged for 0.53.1

**Comment by illwieckz** [comment]
So, let's summarize bugs:

- [ ] dying while underwater
  * low priority, dying happens when the bar is empty then not visible, so it is kept invisible
  * not release-blocking
- [ ] not displayed when spectating someone
  * low priority
  * not release-blocking
- [ ] switching followed player while spectating
  * low priority because it is not displayed when spectating to begin with
  * not release-blocking
- [ ] leaving the team
  * it disappears by itself because it goes down to zero and disappear
  * not release-blocking
- [ ] spawning underwater
  * we can live with this bug for now
  * not release-blocking

**Comment by slipher** [comment]
The wrong approach of basing it on submerging/surfacing noises leads to some inevitable bugs. As already mentioned, it is impossible to implement for a spectated player or to start the timer if you spawn underwater. Additionally, events could be dropped due to packet loss or (maybe) too many other events at the same time, making the timer fail to start or stop.

The right way would be to have a netcode field with the time the player entered water.

**Comment by illwieckz** [comment]
1. Right now it does the job despite some minor graphical glitches that doesn't prevent to play.
2. The actual tree is better for gameplay than adding a commit disabling the feature.
3. The feature is already released and the current tree is better than the previous release.
4. We can implement a better implementation later.

With such status quo, I can start building 0.53.1.

**Comment by illwieckz** [comment]
From a player point of view there are only two graphical glitches that doesn't prevent to play:

- oxybar that disappears by itself after switching team or dying underwater by something else than drowning
- missing oxybar when spawining underwater

From the player point of view the features works reliably in all cases.

I don't see anything blocking a release and requiring a new commit and more talk delaying a release.

**Comment by bmorel** [comment]
> by something else than drowning.

This is theoretically fixed by https://github.com/Unvanquished/Unvanquished/issues/2035
