### ISSUE TITLE
Alien build menu ignores key input after abort

### ISSUE THREAD

**Issue by Gireen** [Unvanquished/Unvanquished#2049]
to reproduce
- open alien build menu
- select building
- abort placement
- try opening menu again

one key event or mouse movement has to be happen that the menu reacts again.

**Comment by RedSkyByte** [comment]
I've reproduced the problem on my machine.
By the way there I've noted a similar problem in human team too, with slight variation:

1. open build menu
2. place a structure
3. try opening menu once more

**Comment by slipher** [comment]
@RedSkyByte has clarified on IRC that the previous comment is referring to being unable to open the build menu immediately after placing a building or canceling placement. This happens due to the weapon cooldown. Although buildable selection (which can be done in the console with `/build`) is not rate-limited, the build menu is normally accessed by doing `+attack1` which is blocked by the weapon cooldown. It would be better if we could open the build menu at any time.

I'm not sure if @Gireen's OP is referring to the same thing or not.

**Comment by Gireen** [comment]
As far as i remember this bug is time independent. 
When there is no mouse movent or other keys pressed the build menu key must be pressed two times to open again after aborting.

**Comment by slipher** [comment]
The circle menu input works quite differently now, so I will assume that this no longer happens.
