### ISSUE TITLE
scoreboard does not always shows the map's name

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2113]
The scoreboard have a place to show the map's name.
This information is only extracted from the `.bsp` file, while not being a mandatory entity. This results in many maps not having any name while seen from in-game.

Instead, the `.arena` file should be read to get either the `longname` or the `name`, and if those are absent, then rely on the map-entity. If still absent, it should probably be explicit that the map have no name, and maybe rely on the filename.

**Comment by bmorel** [comment]
was done by @illwieckz

**Comment by illwieckz** [comment]
Yeah, fixed by https://github.com/Unvanquished/Unvanquished/issues/2114

Actually the `<levelname/>` tag prints `cg.mapLongName` which is set to `arenaInfo.longName` which is always set to something thanks to a fallback. The code to fallback on various available names is on `SetMapInfo()` in `cg_main.cpp` (in worst case, the bsp name is used, which is always the same as the short name).
