### ISSUE TITLE
add a  g_cheat_ignoreBP

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2127]
This cvar would allow one to build even if out of BPs. It would *not* make buildings powered, though.

The intent is to ease the building of layouts. The author would still see the (negative) number of BP, but this would not prevent them to build. This way, a per-layout config could be done to prevent buildings to be disabled.

**Comment by bmorel** [comment]
I assigned myself, but ofc if someone else want to do it, no problem.

**Comment by DolceTriade** [comment]
`give bp 10000`?

**Comment by necessarily-equal** [comment]
For the record, I don't see how your proposal is different (in behaviour) from setting `g_BPInitialBudget` absurdly large. (And perfectly undistinguishable for a mission map if you can disable the CKit).

I'm really confused at what you have in mind, because at least with the implementation you seem to be hinting at, which is that there is still some BP limitation because players are building bases, except there is no BP limitation because things don't get unpowered after they are built (wtf?), it sounds like you have a mix of BP requirements and BP allowance, which is really tricky to get right. You would need to special-case the code that powers things off, do some careful testing to avoid some infinite BP generation hacks (from deconstruction) and probably some more which I didn't think of. So I've removed the "D-Easy" tag.

So what is the difference between your proposal and a large enough high BP budget?

**Comment by bmorel** [comment]
You're overthinking.
I'm just saying that this cheat cvar would allow to skip the check that there's enough BPs.

**Comment by DolceTriade** [comment]
While there is already a command to do this, I think it's a trivial opt in change, so I'm not super opposed to it.

**Comment by bmorel** [comment]
There is no command to do this. The only command around is to give (or take) BPs, which is different.

**Comment by slipher** [comment]
If you want to see the buildings unpowered (which seems like quite a niche use case), then you can simply undo the command you used first. E.g. if you started with `give bp 200` then `give bp -200`. Or if `set g_BPInitialBudget 234` then `reset g_BPInitialBudget`.

**Comment by bmorel** [comment]
My point is to build a GUI on top of that, not to ask people so send commands in console.

**Comment by DolceTriade** [comment]
Arguably a better GUI could be seen as something like this:

![](https://p.mort.coffee/t4X.png)

**Comment by bmorel** [comment]
Arguable, indeed. I'd just have a checkbox "freestyle building" and let people enable/disable that, instead of requiring manual operations all the time.

**Comment by bmorel** [comment]
The problem that this idea suffers from is that cgame can't actually see or set the state of sgame cvars, and I could not find any way to work around this, including using the `rcon` feature, as it's buggy (#2167).

**Comment by necessarily-equal** [comment]
For the record, I realise now I misunderstood what you meant at first, and read "it would make buildings unpowered" instead, which didn't make much sense.

I think such a cheat cvar would make sense actually, even if not extremely useful. I'm fine with a PR that would allow that.

**Comment by necessarily-equal** [comment]
I don't think anybody is working on this at the moment, and since this is about development tools I think we can put that for a later release. We can add it back if someone intends to work on it of course.

**Comment by necessarily-equal** [comment]
See also #2204. I think it would be good to have one cvar for both.

**Comment by VReaperV** [comment]
For GUI, setting/resetting initial BP budget + setting momentum to max and momentum decay to 0, would probably be fine.

**Comment by slipher** [comment]
Closing since the PR no longer has an owner and no one else seemed to think it is needed.
