### ISSUE TITLE
Option needed to read `$LANG` on every run

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2165]
Usually, to try to get an application run without translations, it is possible to run i.e. `LANG=C ./daemon`. With unvanquished, this does not work.
This is especially useful to search in code for the real, original string.

**Comment by slipher** [comment]
I guess LANG=en should work.

**Comment by bmorel** [comment]
Nope.

**Comment by DolceTriade** [comment]
> This is especially useful to search in code for the real, original string.

I don't understand. Maybe this doesn't affect me because my default language is English... I don't understand the ask here? Is the ask here a way to disable translation?

**Comment by bmorel** [comment]
> Is the ask here a way to disable translation?

Yes.
Because you obviously can't grep for a translated string.

**Comment by DolceTriade** [comment]
The default language is hardcoded to "en" (https://github.com/Unvanquished/Unvanquished/blob/master/src/cgame/translation.cpp#L227).

Setting the language cvar to "" would also disable translation. By default, we do try to respect the environment as much as we can.

**Comment by slipher** [comment]
Oh right, I forgot how it works.

> The default language is hardcoded to "en" (https://github.com/Unvanquished/Unvanquished/blob/master/src/cgame/translation.cpp#L227).
> 
> Setting the language cvar to "" would also disable translation.

Both of these statements are wrong. The language cvar defaults to the empty string, but *the first time Daemon is launched* the language is automatically selected (respecting the LANG environment variable). Then the automatically selected value is stored in autogen.cfg. 

To launch with no translations you want `-set language en`. Setting the cvar to the empty string causes it to be automatically detected again.

Do other applications with persistent settings really follow changes in the environment vars? Like if you launch a web browser with LANG=x and again with LANG=y does it come up with different languages each time?

**Comment by illwieckz** [comment]
It works:

```
./daemon -homepath /tmp/a
Warn: Language "French (France)" (fr_FR) not found. Default to "English" (en)
```

```
LANG=C ./daemon -homepath /tmp/b
Warn: Language "Unknown Language" (c) not found. Default to "English" (en)
```

What happens is that the `language` cvar is an archive cvar, so its value is remembered for the next start.

If I'm understanding the things correctly, making `LANG` overriding the `language` will just mean the `translate` cvar will have no effect and we will not be able to provide a way to change the translation from the in game menu.

What we may want to add is a special value for the `translate` cvar (like `default`) to make possible to always rely on the environment while keeping the `translate` cvar an archive, and allowing people to force a language or return to “guess from environment” behaviour.

----

Note that you can already do that if I'm right (given `C` will fallback to `en` because it is unknown):

```bash
( LANG=C ; ./daemon -set translation "${LANG}" )
```

Except the advice to do `LANG=C` is a bad advice that comes from an alternate reality where only ASCII exists: the `LANG` variable also carries the charset.

With most of the tools, doing `LANG=C` would not only configure the tools to not translate the text (usually displaying the text in English as a convention by domination), but it will also configure the tools to process every text as ASCII, which in turn will change the way text is processed, which can produce many bugs and leads to data corruption. Because of that it also means running a tool with `LANG=C` may not be testing the same code as when using the default environment and then may not only add bugs but also hide bugs.

In an UTF-8 environment, the correct way of telling a software to use its default strings is `LANG=C.UTF-8`. If the environment uses another charset, it must be adjusted accordingly. For example one can do:

```bash
# This will transform fr_FR.UTF-8 to C.UTF-8 and fr_FR.ISO-8859-15 to C.ISO-8859-15 but will keep C as C
export LANG="${LANG/*.*/C.${LANG#*.}}"
```

And as a side note, setting `LANG` to something is never meant to force anything, it is only meant to set something. It only forces something if the software running as no other option than `LANG` to set a language. Believing the `LANG` variable is to force a configuration instead of setting a configuration is another misconception of what the `LANG` variable does.

The bad advice of `LANG=C` and all the misconceptions around like the difference between forcing and setting is one of the most resilient cargo-cult advices in the unix-based tech industry, so no one is really at fault: everyone repeats it from people repeating it.

**Comment by illwieckz** [comment]
So this is not a bug but a feature request: we need an option to read `$LANG` on every run.

One suggested implementation is to replace the code reading `SLANG` to set the `translate` cvar if unset, but to set the `translate` cvar to a special value like`default` if unset and read `$LANG` if the `translate` cvar is set to that special value.

**Comment by slipher** [comment]
> So this is not a bug but a feature request: we need an option to read `$LANG` on every run.

Does anyone really need this? The problem OP was trying to solve is "how do I set the language to English/untranslated", not "how do I force the language to be plumbed through $LANG".

If the behavior of reading $LANG on every run until the user explicitly picks a value is desired (questionable), then the ARCHIVE flag can be removed from `language`. (A UI would then be expected to set the archive flag if the user clicks a language).

Having a special value like `set language auto` would be ugly IMO because the language detection code can't run inside the cgame sandbox, so you would need a 2nd cvar to communicate the value that was detected.

**Comment by necessarily-equal** [comment]
To be honest the current situation looks fine to me, but if we don't plan to have a language slider in the settings. I'm also ok with just forcing whatever the OS tells is the language, but I don't think an option in-between (where we would try to listen on the OS language changes and at the same time having a persistant language option) is worth it.

A note though:

> Because you obviously can't grep for a translated string.

You can actually. It's not really practical, because you have to grep in unv.dpkdir for the string, then look at the corresponding message one or two lines above (or just rely on `grep -B4`) to get the english message – and then grep the english message. That's 1 level of inderection, so 2 greps instead of 1.

For the record, it's similar, but not worse than what currently happens with config files anyway, where after finding the code which does something, you need to find where the variable is set, then grab the config key which can have a different name then grep *that* and look for the correct file. That's 3 jumps, a total of 4 grep. Really the translations are not as bad as config files :S (both are manageable though, I'm not saying it's impossible to grep config files, just that if you can do one you should be able to handle the other one too)

**Comment by bmorel** [comment]
> Do other applications with persistent settings really follow changes in the environment vars? Like if you launch a web browser with LANG=x and again with LANG=y does it come up with different languages each time?

Browsers just obey the LANG variable, whichever one it is.
The LANG=C is very important for both debugging AND reporting bug purposes.
Taking firefox, it is set to "french" in it's configuration, but when I run it as `LANG=C firefox` it gives me the "C" locales (which is **not** an english locale!).

About english "being a locale" or whatever you think, I'd suggest you all to run `dpkg-reconfigure locales` if you have a debian derivative at hand. This should give you something like this:

```
                                                        [*] en_AG UTF-8                                                                            │ │  
  │ │                                                        [ ] en_AU ISO-8859-1                                                                       │ │  
  │ │                                                        [*] en_AU.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_BW ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_BW.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_CA ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_CA.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_DK ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_DK.ISO-8859-15 ISO-8859-15                                                          │ │  
  │ │                                                        [ ] en_DK.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_GB ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_GB.ISO-8859-15 ISO-8859-15                                                          │ │  
  │ │                                                        [ ] en_GB.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_HK ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_HK.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_IE ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_IE.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_IE@euro ISO-8859-15                                                                 │ │  
  │ │                                                        [ ] en_IL UTF-8                                                                            │ │  
  │ │                                                        [ ] en_IN UTF-8                                                                            │ │  
  │ │                                                        [ ] en_NG UTF-8                                                                            │ │  
  │ │                                                        [ ] en_NZ ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_NZ.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_PH ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_PH.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_SC.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_SG ISO-8859-1                                                                       │ │  
  │ │                                                        [*] en_SG.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_US ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_US.ISO-8859-15 ISO-8859-15                                                          │ │  
  │ │                                                        [ ] en_US.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_ZA ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_ZA.UTF-8 UTF-8                                                                      │ │  
  │ │                                                        [ ] en_ZM UTF-8                                                                            │ │  
  │ │                                                        [ ] en_ZW ISO-8859-1                                                                       │ │  
  │ │                                                        [ ] en_ZW.UTF-8 UTF-8                          
```

> Note that you can already do that if I'm right (given C will fallback to en because it is unknown):
>
>`( LANG=C ; ./daemon -set translation "${LANG}" )`

This is sick. Just obey the environment variable... this will be just much easier on all POSIX-like systems, which are very likely a non-negligible part of the user-base, and which is clearly the majority of the devs.
Daemon works in enough non-standard ways, do you really love that much that it's a mess to handle?

> Except the advice to do LANG=C is a bad advice that comes from an alternate reality where only ASCII exists: the LANG variable also carries the charset.

![2022-09-06-171428_1362x748_scrot](https://user-images.githubusercontent.com/1316300/188672886-d5e26c60-c354-4c01-b494-f82474abc2b8.png)

> but it will also configure the tools to process every text as ASCII, 

No. If the source code was encoded as UTF-8, then the process text would be UTF-8. LANG=C is basically "use what the code says, without interpretation". It is possible to use UTF-8 in C and C++ codebases, so no, it does not forces ASCII. C++98 is far behind us, now.

> In an UTF-8 environment, the correct way of telling a software to use its default strings is LANG=C.UTF-8. If the environment uses another charset, it must be adjusted accordingly. For example one can do:

See above screenshot about the **STANDARD**. This does not changes anything to the problem discussed though.


> So this is not a bug but a feature request

I disagree, to me it is a bug. Because unvanquished behaves in a surprising way with no obvious way to learn the correct way.

> One suggested implementation is to replace the code reading SLANG to set the translate cvar if unset

Locales are not limited to RMLui, the "tutorial" is also affected, notably.

> Does anyone really need this? The problem OP was trying to solve is "how do I set the language to English/untranslated", 

Yes, people can and do use that feature. Notably people that might be able to do translations in several langs (that's only an example, I would not be surprised if other uses exists).

> not "how do I force the language to be plumbed through $LANG".

This is the idiomatic way that people will use.

> You can actually. It's not really practical, because you have to grep in unv.dpkdir for the string, then look at the corresponding message one or two lines above 

Yes. I could also implement unvanquished with an hexadecimal editor and use an OS that runs with perforated paper. Hey, I could even use a ternary computer!

**Comment by illwieckz** [comment]
As @slipher explained above, you'll get daemon always following the LANG variable this way (but the option has to be kept on each call):

```sh
LANG=something ./daemon -set language ''
```

This is true because `-set language ''` will prevent reading the persistent cvar value. Since Dæmon is POSIX compliant if you set LANG to C it will not only use the default locale, but as an extra it will configure the game to use the default locale.

**Comment by illwieckz** [comment]
> Having a special value like `set language auto` would be ugly IMO because the language detection code can't run inside the cgame sandbox, so you would need a 2nd cvar to communicate the value that was detected.

What if we just do something like `auto:fr` ? If the cvar starts with `auto:` or is set to `auto`, it will read the environment to set the language as a suffix like `auto:fr` or `auto:en` given the environment. When the game reads the cvar, if it does not start with `auto:` it will use the string as the language code, if it starts with `auto:`, it will strip that prefix and uses the remaining string as a language code.

A game UI can display a drop-down menu like this:

```
[Auto: Français ][v]
[English           ]
[Français          ]
[Español           ]
```

```
[English        ][v]
[Auto              ]
[Français          ]
[Español           ]
```

**Comment by slipher** [comment]
> What if we just do something like auto:fr ? If the cvar starts with auto: or is set to auto, it will read the environment to set the language as a suffix like auto:fr or auto:en given the environment. When the game reads the cvar, if it does not start with auto: it will use the string as the language code, if it starts with auto:, it will strip that prefix and uses the remaining string as a language code.

It could work, but not if you insist on having an "auto" option in the menu. Choosing auto won't work since auto-detection is only done when the engine starts.


If we did my suggestion above about removing the ARCHIVE flag from the language cvar, then it would work like Firefox: keep auto-detecting until the user explicitly picks one. And there would be no "auto" option in the menu; the only way to get back that behavior would be `/reset language`, similarly to deleting the config setting in Firefox.
