### ISSUE TITLE
Windows 4K scaling

### ISSUE THREAD

**Issue by DynV** [Unvanquished/Unvanquished#2243]
On Windows at 4K resolution, the UI won't show properly with the recommended 150% scaling; it needs to be put at 100% to work properly and for me 100% scaling is unusable when in windowed mode.

I recommend you either fix the full-screen mode so that scaling doesn't affect it, or alternatively change windows scaling each time focus is given to the game then put back when focus is take from it (so focus on something else).

**Comment by slipher** [comment]
We have [this thing](https://github.com/DaemonEngine/Daemon/blob/13e4aca4e6fcce7f521a8c3df50e380500fe422a/src/engine/sys/manifests/dpi-aware.manifest) which is supposed to stop that from happening...

**Comment by slipher** [comment]
I tried the 150% scaling option in Windows 10 on my (not 4K) monitor, and Unvanquished worked fine. It just makes the window bigger in windowed mode or decreases the effective resolution in full-screen mode.

**Comment by slipher** [comment]
Now I have managed to reproduce it. It turns out that the bug happens only when Daemon is built with MinGW, not MSVC. Not what I was expecting...

The problems seem to be that our XML manifests (the relevant one is linked above in my first comment) are not being included in the binary. Instead, there is only a default manifest provided by the toolchain. [This bug](https://github.com/msys2/MSYS2-packages/issues/454), open since 2016, describes the issue.

**Comment by slipher** [comment]
Fix coming: https://github.com/DaemonEngine/Daemon/pull/952. Turns out the MSYS2 default manifest is not really relevant but CMake ignores .manifest sources in MinGW.
