### ISSUE TITLE
Steering issue: the navmesh generation

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#2265]
So the navmesh generation code was moved into Unvanquished following https://github.com/Unvanquished/Unvanquished/pull/1646. [DaemonMap](https://github.com/DaemonEngine/daemonmap) is destined to be removed but was still used to generate the navmesh for the last release.

On the long-term scope, we should get rid of daemonmap and make the navmesh generator in Unvanquished reliable enough to be used all the time, and enable it by default.

What's the current state of things, and what do we need to make that happen? Can we make a todo list?

ping @slipher, @DolceTriade and @illwieckz I guess, as you are involved in navmesh generation and/or release preparation.

**Comment by slipher** [comment]
The big blocker is that I couldn't figure out why lazy initialization of navmeshes wasn't working (#1765).

**Comment by necessarily-equal** [comment]
Ok! I should have a fix for that in https://github.com/Unvanquished/Unvanquished/pull/2272. What would be the other problem(s)?

**Comment by slipher** [comment]
1. We need a better story for automatic nav generation on servers (it's already working well for local games, cg_navgenOnLoad). A bare-bones setup is possible now by adding a `navgen missing` command in the map config before any `bot fill` commands, but it needs improvement: (a) needs to be more automatic -- this requires issuing a command and won't work with the new g_bot_defaultFill cvar; and (b) causes the server to freeze for up to tens of seconds, so we might want to make it run "in the background".
2. I have a commit to add more info to the navmesh file header to ensure the cached navmesh is invalidated and regenerated if the BSP/navgen algorithm/etc. changes. I haven't merged that since it breaks compatibility with existing navmeshes. I intended this for a next-release branch but if (1) is solved well enough we might merge it to master.

**Comment by DolceTriade** [comment]
> We need a better story for automatic nav generation on servers

Agree. I think we should come up with an end goal too. For instance, is automatic nav generation meant to replace navmeshes shipped with dpks? Is it only meant as a fallback for when navmeshes are missing. Further, some maps might require different parameters to build optimal navmeshes: will we have a mechanism to allow tuning of this?

**Comment by necessarily-equal** [comment]
> Further, some maps might require different parameters to build optimal navmeshes

Apparently, there are a few such map in Sweet's server. For now, this isn't something we rely on so there is no regression about that but we may do it eventually, for example adding stuff to some map arena file https://github.com/Unvanquished/Unvanquished/pull/2255. Maps can just generate their own navmesh for the time being. This is supported now and likely will stay later.

**Comment by slipher** [comment]
> For instance, is automatic nav generation meant to replace navmeshes shipped with dpks?

Yes.

> Further, some maps might require different parameters to build optimal navmeshes: will we have a mechanism to allow tuning of this?

We can have a config file, which (like navmeshes) is searched first in \<homepath>/game/ and then VFS.

**Comment by illwieckz** [comment]
> Further, some maps might require different parameters to build optimal navmeshes: will we have a mechanism to allow tuning of this?

> We can have a config file,

Along config files, we can also define map-specific objects or materials. The reason why I haven't implemented botclip is that I don't want to implement it in daemonmap then port it to the gamecode. I also want to implement a specific texture named “outside” that would be used by the map compiler to add slick/clip surfaceparms but also prevent navmesh generation, but yet again, I don't want to implement it in daemonmap then port it in the game code. Other surface parms or content parms having an effect on the navmesh may be imagined.

The gamecode of a mod itself may tweak things (adding player classes, tweaking their sizes…).

> For instance, is automatic nav generation meant to replace navmeshes shipped with dpks?

Generating the navmesh in the game code is the only way to be 100% sure the navmesh matches the gameplay, so shipping a navmesh in a dpk is a workaround to release the game early.

**Comment by DolceTriade** [comment]
So what I'm getting from this is:

 - Navmeshes generated on start up when missing. No bots for the first X minutes of gameplay while this happens. Afterwards these will be cached somewhere intelligently so hosting/playing different mods or something will not continuously invalidate the cache?
 - Allow mapper to pass in a config somewhere to tune navmesh generation per map

This SGTM if this is the plan.

**Comment by necessarily-equal** [comment]
So I've thought about it, and I think we can have this design for filenames. For that, we change the filename of the navmesh file to include the navmesh format version:

```diff
diff --git a/src/shared/bot_nav_shared.h b/src/shared/bot_nav_shared.h
index b1d539cc8..43d7af632 100644
--- a/src/shared/bot_nav_shared.h
+++ b/src/shared/bot_nav_shared.h
@@ -270,9 +270,12 @@ inline std::vector<class_t> RequiredNavmeshes()
        };
 }
 
-inline std::string NavmeshFilename(Str::StringRef mapName, Str::StringRef species)
+inline std::string NavmeshFilename(Str::StringRef mapName, Str::StringRef mapVersion, Str::StringRef species, bool insideDpk)
 {
-       return Str::Format("maps/%s-%s.navMesh", mapName, species);
+       if (insideDpk)
+               return Str::Format("maps/%s-%s-v%i.navMesh", mapName, species, NAVMESH_VERSION);
+       else
+               return Str::Format("maps/%s-%s_%s-v%i.navMesh", mapName, mapVersion, species, NAVMESH_VERSION);
 }
 
```

If the file exists inside the dpk, then it is loaded from the dpk. For the file to be found, it will have to have the same navmesh format version. If the file isn't found, then it will have to be generated, and will be stored under a name that includes the map version. This is to ensure that a new release of a map without navmesh still gets new navmesh.

Does that design sound reasonable to you all? @slipher I'm not sure I get what you mean with "add more info to the navmesh file header to ensure the cached navmesh is invalidated and regenerated if the BSP/navgen algorithm/etc. changes". There is already `NAVMESHSET_VERSION`? It's already at the beginning of the navmesh file?

**Comment by slipher** [comment]
I don't like the idea of putting the map version in the navmesh file name. If the server updates the map it is better for the old file to be overwritten rather than leaving it around forever. *Clients* often go back and forth between multiple versions of the same map via switching servers, but the multiple versions situation should be rare for *servers* which is where the navmesh lives. So I find it best to put the information for detecting map changes (pak checksum if available, perhaps bsp file modification time...) in the navmesh header.


>  There is already `NAVMESHSET_VERSION`? It's already at the beginning of the navmesh file?

These version numbers may turn out to be useless in practice because no one updates them. For example no one ever updates the IPC version numbers, which is why you get a totally uninformative error message when you load a gamelogic from the wrong version. I don't remember exactly what I had in mind, but I have a commit on my PC which adds some additional checks.  Is this urgent or can it wait ~1 week until I get back to that machine?

**Comment by necessarily-equal** [comment]
Nothing urgent indeed

**Comment by slipher** [comment]
The main server-side navmesh generation was merged: #2353. What remains to have this released is:

- Enable cvars for navmesh generation by default (`cg_navgenOnLoad`)
- Improved cache invalidation (https://github.com/slipher/Unvanquished/commits/navgen53)
- Remove daemonmap from toolchains (Urcheon, NetRadiant)

**Comment by illwieckz** [comment]
> - Improved cache invalidation (https://github.com/slipher/Unvanquished/commits/navgen53)

Do we need that for the release?

**Comment by necessarily-equal** [comment]
This issue seems to have been superseded by https://github.com/Unvanquished/Unvanquished/issues/2403
