### ISSUE TITLE
Extra navmesh parts in Chasm base

### ISSUE THREAD

**Issue by necessarily-equal** [Unvanquished/Unvanquished#2389]
```
/devmap chasm
/navedit level3upg
```

![Screenshot from 2023-01-30 09-50-51](https://user-images.githubusercontent.com/59283660/215430971-43eac8e6-7d94-4598-ab72-7d3e953848ec.png)
![Screenshot from 2023-01-30 09-50-44](https://user-images.githubusercontent.com/59283660/215430976-d7e3bb71-96fb-485f-9a50-a058c5f846ad.png)

These connections shouldn't exist, because otherwise bots will get stuck trying to go through them.

I suspect this is a consequence of disabling the patch blocks here: https://github.com/Unvanquished/Unvanquished/blob/master/src/shared/navgen/nav.cpp#L313. @slipher do you want to have a shot at porting this?

**Comment by slipher** [comment]
OK, I'll take a look at porting that bit

**Comment by bmorel** [comment]
As I said on IRC this morning, I remember when I still had the embedded navgen in my codebase that aliens did not had problems moving out of their base, and chasm is the map I had a layout to prove a pair of bugs in this mechanism.

So, I do not think the problem is that old. But maybe my memory does not serves me well.

**Comment by necessarily-equal** [comment]
Should be fixed by https://github.com/Unvanquished/Unvanquished/pull/2402
