### ISSUE TITLE
Killing yourself makes you lose credits/evos

### ISSUE THREAD

**Issue by VReaperV** [Unvanquished/Unvanquished#2456]
Dying to your own weapons (e. g. lucifer cannon, grenade, firebomb, flamethrower, dragoon snipe) makes you loose credits/evos upon death. You already lose all of your equipment/alien class on death, further penalizing the player because they just happened to die to their own weapon in combat makes 0 sense.

**Comment by VReaperV** [comment]
> Ah, we should also check if suiciding with `/kill` (sometime handy when stuck in some maps) doesn't remove credits either, losing equipment is bad enough.

`/kill` doesn't seem to take away any credits, just killing yourself with a weapon you have.

**Comment by sweet235** [comment]
Easy to fix, here: https://github.com/Unvanquished/Unvanquished/blob/4d93a66cd77ce96fab329ef1191b16b4009b8546/src/sgame/sg_combat.cpp#L427

This line is a little suspicious, since

- `attacker == self` seems to imply `G_OnSameTeam( self, attacker )`
- there is a redudant pair of parentheses, since 38272099077f7f50e8d7d3b98b3cdb825c92e00f (over 10 years ago)

But I'm not entirely sure I understand what was going on there.

**Comment by sweet235** [comment]
In fact, it has been like this since 98b3a1480522dbd90660ee4c6bc91f6d80885286, suggesting that GPP already had this. I think we can change it.
