### ISSUE TITLE
Portals are rendered on top of building outlines

### ISSUE THREAD

**Issue by VReaperV** [Unvanquished/Unvanquished#2476]
When using a ckit or granger, portals are rendered on top of the outline of a building you're trying to place:
![unvanquished_2023-03-09_005331_000](https://user-images.githubusercontent.com/10687142/224059553-1b25c0d2-647d-457e-98a8-7b5dd8d04922.jpg)

**Comment by illwieckz** [comment]
They are also wrongly rendered on top of textures. We can see that other problem in pulse map where a texture should be applied on the camera screens but is not.

**Comment by illwieckz** [comment]
About portals painted over texture instead of the other:

Tremulous:

[![portal over texture](https://dl.illwieckz.net/b/unvanquished/bugs/portal-over-texture/20230313-183015-000.tremulous-pulse-camera-portal.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/portal-over-texture/20230313-183015-000.tremulous-pulse-camera-portal.jpg)

Unvanquished:

[![portal over texture](https://dl.illwieckz.net/b/unvanquished/bugs/portal-over-texture/20230313-183122-000.unvanquished-pulse-camera-portal.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/portal-over-texture/20230313-183122-000.unvanquished-pulse-camera-portal.jpg)

**Comment by bmorel** [comment]
@illwieckz : which map is this?

**Comment by illwieckz** [comment]
> We can see that other problem in pulse map where a texture should be applied on the camera screens but is not.

😉️

**Comment by bmorel** [comment]
Oh, it's in the space station? I could not recognize the screenshots :)

**Comment by cu-kai** [comment]
This also reveals another bug with portals: you cannot render a skybox through a portal.

**Comment by illwieckz** [comment]
Fixed by:

- https://github.com/DaemonEngine/Daemon/pull/1018
