### ISSUE TITLE
allow layout files to add models with linked entities or linked to one of said map's entities

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2525]
The idea is to be able to place "point of interests" in maps, such as a place to reach to win, without having to modify the map.

It could also be used to test bugfixes without actually modifying the .bsp, which would  make the process a bit faster, legal in all cases (including when the author does not want people to modify the map) and less dangerous (editing a binary file is not the most trivial thing to do)

**Comment by DolceTriade** [comment]
This should not be a layout feature. This should be a map construct or something like Lua.

**Comment by bmorel** [comment]
You can already do that in maps natively (exactly the same applies to the .layout feature), even if the details regarding models are still unsure (read as: currently nobody around seems able to use i.e. func_door_model).
This feature request is merely about allowing one to place other things than just buildings, without editing a map.
There are several reasons why one would want to do that:

* map source is lost. Happens most of the time.
* Licence prevents modifying the original .bsp file (and possibly other files inside the .dpk). Happens fairly often too.
* someone wants to adapt a map to a specific rule set, but does not knows how to use NetRadiant

For example it would be possible to make thunder into some sort of escape mission (with one team starting at some point and having to reach, and possibly stay a while there, a specific position) or other adaptations like this.
I do not think a full blown programming language is required for that, especially since the entities currently present already allow to implement the feature modulo the mystery about func_door_model.
The only things to do are to patch sgame to let .layout file load more entities and build some interfaces on top of that.

**Comment by DolceTriade** [comment]
I totally agree with your reasons for why someone might want to do this and think this should be supported...just not with layout files.

I don't think there is an expressive enough way to encode all the information we might want to encode for a given entity that is flexible enough to be useful in a text format.

FWIW, my Lua patchset supports this today and I think this is a far better approach than trying to create a text file to store this info.

**Comment by bmorel** [comment]
> FWIW, my Lua patchset supports this today and I think this is a far better approach than trying to create a text file to store this info.

Depends. Is there is a way to generate the lua files you mention from the game? If it requires modifying a config file manually, I'm not convinced it's as good as improving layout abilities.

**Comment by DolceTriade** [comment]
While there currently isn't a way to generate the Lua files directly, that doesn't mean it can't be done. You could generate stub code to place the entities and then you go in and write code to take action upon touching, killing, hurting, using an entity.

Even without code generation, it's actually quite easy to create arbitrary entities (but its a little more manual. You have to `noclip` to where you want to place the entity and run `viewpos`, and then use that viewpos to place the entity.) 

Furthermore, often people might want to trigger actions based on existing entities (like teleport if you touch an egg to another egg). How would you extend the layout file to account for these types of usecases that seem totally expected if one were trying to create a mission map or something?

**Comment by illwieckz** [comment]
We may just want to be able to load externalized entity lump if it exists as a separate file, the same way we load external lightmaps?

**Comment by bmorel** [comment]
Is not this more or less what the .layout files are?

**Comment by illwieckz** [comment]
If there are more features supported by BSP entities than layout files can do, they would be supported without having to implement anything more than just loading this file from outside the bsp file.

`q3map2 -exportents plat23.bsp` will export `plat23.ent`,
`esquirel bsp -ib plat23.bsp -oe plat23.ent` will do the same.

**Comment by VReaperV** [comment]
This has been done in https://github.com/DaemonEngine/Daemon/pull/1062.
