### ISSUE TITLE
bots do not target disabled buildings

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2540]
to reproduce:

* force bots to use painsaw
* place a node+armoury in front of a barricade hiding an egg
* give aliens a negative starting BP amount
* add a human bot

**Comment by bmorel** [comment]
I think too. This is very likely trivial to fix, I only created an issue to avoid forgetting about fixing it. It's also a minor problem as buildings are very rarely disabled anyway. This causes some stupid behaviors with my PR that improves the fighting code, such as bots shooting with blaster on an egg hidden behind a barricade instead of using their painsaw, but again, that's a rather minor inconvenience that I'll fix later: when my PR will be merged, I'll open a bug to describe this behavior and why it's wrong. Which I'll use as a reminder.

**Comment by DolceTriade** [comment]
Seems like a real issue with a trivial fix. Let's fix this for 0.55

**Comment by DolceTriade** [comment]
Actually, I suspect this is fixed with https://github.com/Unvanquished/Unvanquished/issues/2641
