### ISSUE TITLE
Bots do not see buildables until their construction is completed

### ISSUE THREAD

**Issue by sweet235** [Unvanquished/Unvanquished#2788]
This is because we made bots rely their team's beacons to locate enemy buildables. It turns out that you do not get such a beacon by staring at an enemy buildable during its construction. You get the beacon once it is complete.

Currently, this results in a rather strange user experience: like being able to watch a few human bots passing by a constructing overmind and not seeing it.

**Comment by slipher** [comment]
I guess that behavior makes some sense for friendly buildables since the beacon only appears when you can use them and the beacon sound gives some notification when it is ready. But for enemy buildables definitely not. The humans should not get a notification when the overmind is up. Seems like something that should be fixed on the beacon side.

**Comment by sweet235** [comment]
> I guess that behavior makes some sense for friendly buildables since the beacon only appears when you can use them

That makes sense. So I propose we change handle constructing enemy buildings the same as completed enemy buildings.

**Comment by slipher** [comment]
The fix is in #2845. The thing with beacon notifications upon construction of friendly buildables was a red herring, as the bug was in the line-of-sight tagging code which only applies to enemy buildables.
