### ISSUE TITLE
regression: alphaGen portal keyword not supported

### ISSUE THREAD

**Issue by bmorel** [Unvanquished/Unvanquished#2800]
This warning can be seen in map nova, and is very likely one of the reasons why the cameras in the space station do not work, in combination of other breakage in daemon's renderer that I believe @illwieckz might have fixed, but are still not merged?

**Comment by illwieckz** [comment]
There is no known bug in current (`master`) game / engine about rendering nova cameras.

Unless I miss something:
- One is not working because it is not implemented in the map, basically “the map is not finished“.
- Two are only watchable from very close _because_ the material explicitly request the engine to stop rendering them when not very close, basically “the materials are asking the engine to do something wrong and the engine does what is expected”.

Though, we still have things to implement in engine about portals that can affect the way rendered cameras are blended with other textures to produce special effects.

It is assumed the missing of `alphaGen portal` prevents to blend textures on cameras or to blend cameras on textures, but this do not prevent portals to render.

It is the same problem that affects pulse map camera: the camera renders, but the blending of some effects with the rendered camera surface don't work.

This is a regression compared to Tremulous, not compared to Dæmon.
