### ISSUE TITLE
main menu should be split from cgame

### ISSUE THREAD

**Issue by ghost** [Unvanquished/Unvanquished#2808]
Main menu requires loading whole cgame for zero technical reason. This slows down the start of the game, slows down map loading, too. Too many things are loaded to never be used, which even prevents modding the main menu, which can not lead (obviously) to cheating, since it's only about starting a game with some specific parameters. Joining an internet game is one of the use cases, but then you still have to re-load the server's cgame.

Splitting cgame in main-menu and cgame would lead to ability to mod the main menu and would fasten the load of cgames.

**Comment by slipher** [comment]
Can you identify a specific thing that we load in the main menu which does not need to be loaded, and occupies a significant amount of time?

**Comment by DolceTriade** [comment]
Modding the main menu is already possible until you connect to a server.

Separating the CGame and the Main Menu will only allow modding the ESC-menu, not the HUD. Furthermore, I think it is already safe to modify the esc-menus on a pure server since the menuContext is separate from the HUD context...

We should think of a solution that will allow us to mod both on a pure server.

maybe the right solution is to disable Lua for the HUD context but allow it for the menu context. Currently, no HUD elements rely on Lua.

Further, there is a technical reason: nacl nexes are big and the UI would be another big nexe we would end up having to ship (x3 since one for each architecture. You *could* argue that we should no longer ship the x86 nexe, and only ship x86_64 and aarch64). That's not great. This was the motivation behind merging the two in the first place.

**Comment by bmorel** [comment]
> Can you identify a specific thing that we load in the main menu which does not need to be loaded, and occupies a significant amount of time?

When you load the main menu, all the game resources are also loaded. This have 2 consequences:

1. main menu is slower to load
2. logs are full of useless noise

> Further, there is a technical reason: nacl nexes are big and the UI would be another big nexe we would end up having to ship 

Most modded servers do *not* ship all the parts already. AFAIK I'm the only mod host candidate (my server is mostly down those days) to provide a locally playable mod.
This size problem would only affect releases, which happen rarely enough to not be a problem.
This point leverages the question of: what's the size of the main menu's resources and binary?

Feel free to close this if you disagree.

**Comment by DolceTriade** [comment]
Can you explain "all the game resources also are loaded"? We load the unvanquished pak and all of its dependencies, yes...but that's not loading any models or anything. We only load the UI and things required to load the UI into memory...

**Comment by slipher** [comment]
Closing this as no actual benefits to a separate main menu VM were identified.
