### ISSUE TITLE
Compiler-unsafe usage of GLM vectors

### ISSUE THREAD

**Issue by slipher** [Unvanquished/Unvanquished#3013]
Recent issues regarding diabolical UB-exploiting compiler optimizations prompt me to bring this up. GLM vectors are implemented somewhat like this:
```
class vec3 {
	float x, y, z;

	float operator[](size_t i)
	{
		switch(i)
		{
		default:
			case 0:
		return x;
			case 1:
		return y;
			case 2:
		return z;
		}
	}
};
```

For compatibility with non-GLM parts of the code which expect an array of 3 floats, we often do as follows:
```
glm::vec3 vec;
some_function( &vec[ 0 ] );
```

This is undefined behavior because we are really just using the address of `x`, which is not part of an array. Compilers could potentially exploit this and break our code. Currently, compilers don't seem to do anything with this, but who knows what the next version may bring?

**Comment by illwieckz** [comment]
Could have it been possible for GLM to make it an union of `float x, y, z` and `float[3]` instead?

Actually I assume compiler wants to store `float x, y, z` as `float[3]` in memory, because it allows themselves to optimize code, for example when doing `function(x, y, z)` they will likely do `function(&x[0])` already and then later do SSE code on the array directly.

I noticed it when working on some part of the engine with functions taking many arguments that could be part of a single struct, and most of the time the compiler was able to generate SSE code that spans over the multiple arguments as if it one a single array from the start.

I'm in favor of finishing that GLM migration anyway.

**Comment by illwieckz** [comment]
> Could have it been possible for GLM to make it an union of `float x, y, z` and `float[3]` instead?

Well, according to some comments from there: https://stackoverflow.com/questions/494597/c-member-variable-aliases

This would be considered ugly non-standard “pre-K&R 1st Edn” code, I'm a dinosaur.

**Comment by slipher** [comment]
Configuring GLM to use the union-of-anonymous-structs layout and adding an array to the union might be a good idea. Although this too would lead to a lot of undefined behavior (accessing an inactive member of a union), it would probably be less risky than what we do now, since accessing inactive members of union is indeed a popular idiom in crusty C code. For example, the `floatint_t` struct that I'm nuking in https://github.com/DaemonEngine/Daemon/pull/1156. Exploiting that variety of UB would break a lot of users.

**Comment by illwieckz** [comment]
I guess an alternative without undefined storage layout could have been:

```c++
struct vec3 {
	float v[ 3 ];

	float& x()
	{
		return v[0];
	}
	float& y()
	{
		return v[1];
	}
	float& z()
	{
		return v[2];
	}
	float& operator[](size_t i)
	{
		return v[i];
	}
};
```

But then people would have to write `v.x()` instead of `v.x` and it would fail at mimicking GLSL.

**Comment by illwieckz** [comment]
Is there some compiler-specific builtins to tell that `float x, y, z` should always be stored as a consecutive list of floats in that order?

**Comment by illwieckz** [comment]
What would be awesome is that if C++ allowed to overload _members_, with a syntax like this:

```c++
struct vec3 {
	float v[ 3 ];

	float& member x()
	{
		return v[0];
	}
	float& member y()
	{
		return v[1];
	}
	float& member z()
	{
		return v[2];
	}
	float& operator[](size_t i)
	{
		return v[i];
	}
};
```

The feature would be implemented to allow us to not write the `()` when calling the overloaded member, so with `vec3 v` we could do `v[3]` as well as `v.z`. I should submit that to be part of C++ 2042 standard. 😜️

**Comment by slipher** [comment]
> Is there some compiler-specific builtins to tell that `float x, y, z` should always be stored as a consecutive list of floats in that order?

That's guaranteed by the struct layout rules. In C++ they are the same as C, unless the class/struct has a vtable or uses more than one access level (public/private/protected) for its data members.

I just noticed that the `Color` class does the same thing we have been doing with GLM: members declared separately (`component_type red = 0, green = 0, blue = 0, alpha = 0;`), but offers a pointer to `red` to use like an array. Fortunately these fields are private, so it would be easy to rewrite it to use an actual array.

**Comment by illwieckz** [comment]
> > Is there some compiler-specific builtins to tell that `float x, y, z` should always be stored as a consecutive list of floats in that order?
> 
> That's guaranteed by the struct layout rules. In C++ they are the same as C, unless the class/struct has a vtable or uses more than one access level (public/private/protected) for its data members.

So, does that mean accessing “the adress of y” as “the address of x + 1” is not undefined behavior?

It makes sense that struct should be super stable and its layout not modified by the compiler for optimization purpose. What if you use a struct for writing a file and reading it again, with some years in between after recompiling the software, or on another system? What if you use a struct to write or read a packet, with people using the software compiled by their own distro for their own system on every side of the network?

If the struct layout is guaranteed, then there may be a branchless alternative for the original snippet:

```c++
struct vec3 {
	float x, y, z;

	float& operator[](size_t i)
	{
		return *(&x + i);
	}
};
```

Or maybe better:

```c++
struct vec3 {
	float x, y, z;

	float& operator[](size_t i)
	{
		return (&x)[i];
	}
};
```

**Comment by illwieckz** [comment]
In `glm/detail/type_vec3.hpp` there is some interesting code with some define for configuring anonymous structs and compiler pragmas.

**Comment by slipher** [comment]
> So, does that mean accessing “the adress of y” as “the address of x + 1” is not undefined behavior in a struct but is in a class?

It does not mean that. `struct` and `class` work the same.

The rule is that pointer arithmetic is only valid within the boundaries of an array. A non-array object is treated like an array of length 1. So dereferencing `&x + 1`, or evaluating `&x + 2` are undefined behavior, regardless of whether the layout is guaranteed.

**Comment by illwieckz** [comment]
So I guess this is not undefined behavior, while being branchless:

```c++
using vec = float;
struct vec3
{
	vec x, y, z;

	vec& operator [](size_t i)
	{
		vec* v3[3];
		v3[0] = &x;
		v3[1] = &y;
		v3[2] = &z;
		return *v3[i];
	}
}
```

And this would rely on the ability of the compiler to drop the extra copies because the compiler knows its own internal representation and knows the variables are properly packed like an array.

I have an exemple [there](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGEgBykrgAyeAyYAHI%2BAEaYxHoADqgKhE4MHt6%2BAaRJKY4CoeFRLLHxXLaY9vkMQgRMxAQZPn5cgXaYDmm19QSFkTFxegp1DU1ZrbYjvWH9JYNcAJS2qF7EyOwc5gDMYcjeWADUJltuyMP4qMfYJhoAgje3zGwKCUzrBwoAbg8mAOxWdxuAE4vCkjAdPh0jlsACIHKi0VBMAjHAH3QEaIHDYheBwQjpbH6Yv5o4HAyHIA6qUgHACeNIAXqiieigeSOuYAGwHVAJOLIkhHACsViFMIgKQZmAA%2BgQDngFkS2cT/j8zDsqAcsDRwugIG4APLKACS2CEioxyqtFIAVBDCSKHTDmZayZjPg6LBoTGLoXCuaoXay3UCPT6LFwff7YUczJzaUGQ%2BTPWYo37Y5ymVtScTc0DiJgCKsGAcbWGRXgo4n1ZUlEqQwWi8QSxAA4qK1Xs2qtq48FR6yrnRjg%2B6CTy%2BcQBcRSxAKVt7RaR2zVa683ODsRCV3V1bNwA6VTpw92j0HxN54H72np68nrZ7hPbpeX%2B8M9Nvu97rM5q2XwvFjctx/MlfiHYNQMTCCnweT5UDwdAPkLaUuAlT4QBAOcuXtUglS%2BdCKSpGk8IwqF6Q%2BNCSMpBlFxJJVT0PY44UDaD3Xva9GLpc9Q1fd9ILAmC4IQpQCGlMxUPwgksI9HDLWIgjqXIiTKTIuSoWon4V1ZcsvTTDjmJ/bTI19DjHwMlNdJjb8NP4u5YPgg4WC8WhkPEyjCTjHkthk1lVOQdzuSYLzFLcjNoi2GjNOBVB7wYmNAoPUsDjCs8WKBaKH3TeLbyStiuPSt8OPij8cq/PiWTshDHOcsTfP8zzvOBWqsMCoiKPXLkwoin9ovDb1jLiz0%2BrhO0wt6ztus9IzozhQLwymxLRpFKa8vM/qZtW4acvDVMxTK4cKocpzpS2VzMI86KGsxJqPJa4L2rjTqNImzL5xGoDrI4JZaE4IVeD8bheFQTg3GsawPhWNZMFjLYeFIAhNE%2BpYAGsQC2e8tn8SQpCkTkhSBfwYbMfROEkP6EdIIGOF4BQQA0OGEaWOBYBgRAUFQFgEjoOJyEoNAOa5%2BI9kMYBWi4OmaFoAg4hpiBonJ6IwnqWlOFhhXmGIWkDWibQOnhgHSD5thBANBhaGVjgtFILBoi8YA3DEWgaf1rAWGF8QLd4fAC06SEnctzBVA6LwpZV3gwil76Pf0PBoknDWPCwcmCGIPAWFD0hIWIaJkkwGFMFdoxaDCUAPaWBEmGABQADU8EwAB3A0%2BX%2B2H%2BEEEQxHYKQZEERQVHUKPdCJgwjBQUHLGj6IacgJZeWqJ2AFoDXneeqCoJhhnn12CAQQHM5TrAp4gJZ2k6ZwIFcMYWiCBh0D6YpSkSZJUgES/H7yNI74GMoKiqLoplf8oJ9qjdAaJ/OY39hg9AAZMHoYCH6LGWKsdYEgvo/TJlHSmVJ/CcnnpySQBwhbglaHuLge4NAHAgLgQggptiLF4HrLQCwlgIEwEwLA8Qj7Ew4KTUgaczBClIP9S2lNqa03pqXUgTNWZ805vQMgFAIAyIFigYeIt/Biz4HQKWxAZZyyjmrJW6cDEay1jrBw6dDaMAICbM25Nra23trQR26cXZuw2JbL2us8C%2B3JgHIOId9bh0qOTIusclYJ3cfQlOad9aZ2zkoPOBdgBFxHhI8ulca710bowdOrdhCiHEF3PJvc1Dk10OUVRo9LDWAnofGeCQ56cEXsvVe68CCb2RAgA488YSGhNGaXecR96YDqT/LxZ8L6eGaHoEIMx77zByE/ao0DcjPwYHAhZQC/5QKmeMMZp8ahTA2RA/%2Buyr6QNAXMr%2BKDEGQxuZHX6gjyaYNUNg3B%2BDCHAAOMQ0h5DKH4CINOWhCx6EM2RiAIU95/C/A0NCrYQoNBmF%2BL8SF0hI48L4QIoRgNOCiLpgwz6kiWYQCQEouRPNFHs1kYMEWWNNGS2lpQPRltjHm1VorEx2tdYWPZkbaxptzYeMwDbO2Dsnaw1cYXSJVs8De0cD4qOfjkDBw2LDIJkdLahLjrSCJSdonpziTnRJbti4Mz4AYDJtcG5N1ybIduhTpDFKUKUgeqN9DCyqVYceoTRmzzSAvJe3TWkby3jvCme94IjPgMfSo4y/DnxvtA2ZRRrnlFWcss5b81nHKGLGg5IDGiZsAXm4BRyrngKGKczI5yy0porQghQENkEIIeeg4RnAsE4LwQcYAyBKRSBIRQqhgLoZ0PEYw1B3DeB8MkHuIE86F2LsXZyJ5GDcW2DEQSxmxLSVUoFhSslNLsb0u0bo%2BWHK2W8FZaY7l%2BtLHGwFXY4VDixUuPzm4uxsqvEKv9oHZVAS1WCGCVHLV4SMDSuTqnA1cR4m53fYXU1aSLXVytdk5uvA8n2s7o62QJT%2B6W10Gij1phqnepjr6hp/qmmBpXmvENnTum9KNKaIQgziDDNGVsiZiai3X1vuW%2BBiz34v14%2Bmj%2BAnNklu2aMXjXHDmwIkycnZ1bK0KbrfA4%2BTbO6TsediimHbXldvwb2/ts6uBDoBTQ9UY6t2ToxSAfhq721Uw3fisFpAUZbE5HuLYvwtgaF%2BJyLgWwzABY0EKFdkcthtpxS5rdRL4AkpACsAgCRg4Hr3XIiIrANiGfeT2vt3yzO8EwJZ/eehMMFOw93eQzr8M6D0HXScCRQ46Zi/pjgBpg5pblKgTUeXu2fO%2Bf4EhZCKEeH5nI0dILx2Iw86jDQe4zCSCRf4ZbGguBAkkJyGGXCeF6ZEa52bTCuFmHa4d2zGdpZpBAJIIAA%3D) comparing the UB `(&x)[0]` trick and the “copy to an array and access this array”, and both GCC and Clang produce the same code in both case, while the second case may not be considered UB.

So now I wonder if we can have some inline `VEC2GLM` and `GLM2VEC` functions doing similar trick by doing a copy to an array and relying on the compiler to drop the extra copy because the compiler already knows the memory layout is the same even if a struct and an array is not the same from a language definition point of view.

**Comment by slipher** [comment]
To clarify, this issue is *not* about GLM's implementation of indexing allegedly being inefficient. The problem that I reported in the OP is that our own code takes the address of `x` and then uses it like an array, which is undefined behavior.

To identify instances of this pattern, I plan to write something using Clang's AST inspection capabilities.

**Comment by illwieckz** [comment]
> To clarify, this issue is not about GLM's implementation of indexing allegedly being inefficient. The problem that I reported in the OP is that our own code takes the address of x and then uses it like an array, which is undefined behavior.

Yes but this is a good example of accessing a struct like an array, so I kept this as a use case to not have to write an example requiring `VEC2GLM`/`GLM2VEC`. 😅️

Though I don't know yet if that trick can be done for `VEC2GLM`/`GLM2VEC`, but I had the intuition we may write the code in a way the _compiler_ decides it's the same memory, not _us_ deciding it's the same memory in the back of the compiler. I found that allegedly inefficient example simple and short enough to write a PoC whose compiled output would be not too complex to read and to compare. Maybe that theory can be applied to other use cases.

**Comment by illwieckz** [comment]
It looks like this theory of “_let's copy to an array and let the compiler optimize to avoid copies and do direct accesses according to its internal representation_” can be applied to `VEC2GLM`/`GLM2VEC`, as seen [here](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahUAUgBMAIUtXyKxqiIEh1ZpgDC6egFc2TEAtydwAZAiZsADk/ACNsUhAAdlkAB3QlYhcmL19/QPI0jOchMIjotjiE5PtsR2KmESIWUiIcvwCeGrqsxuaiUqjY%2BIMlJpa2vM7RvoHyyqkASnt0H1JUTi5LAGZw1F8cAGozLY9UUcJ0Y9wzLQBBbd397COT5tIWAE8rm/u77Zw6BEDgBJSIhUG4EQ/aEWHY0A4A8LYTAQUHgyKQhbQrQATn%2B2EBzzREIO4XoSJhW1qKmxeNhiKBxIxlPcBBo2NurA4ShSLHWByUADdoYkbH9cT4MiYDoLsKgXgARA40ejoFhEY5i3440akHxOGVyra0syik242Xy9TkA4fG0AL01JsSCqdfxdbt%2Bt0l4WAhvEAH0iIrlar1Z6fdLLVsWEGQ%2BcQCA3p9jh5LbHg%2BRjVtrlstT9I37LXHjkqVWqNXmC1Ki0aS1slcWNQBWKzG5uuqvi25M3D%2BmNxkQANQstwAShAhYno5YAGwyrZY935i1GjMLliem44wUxsytrT7pWlhcAOnUW4te9bPCPId3p6%2BXe1u83rYsd5PD8dz%2B3pGwRCrEwG5bh63b4oSBzDhYQ64B4EC7gsUEjuOCGLqemDqiwEBLl6vYCoK05GgcsEeBYw4IXWGoWPOu5ELhporjqhEgNGC6XjuWznveWwtlYh4dhxD4fDxfG3oJv5Xqe9qifuVgfhJTH/oBpDAbuoGuuB9IEkiJFyiQpAiABEAyja1q2g6BxISZJmClZckHFoRwdiGJnqFZNq2fZrYHDwznHg2BwmSJSxBTK3lWAcFj%2Ba5BwyUhDF3IK6AEJgBwpKQ4REAGu6TixbGISKTEZVlNAQJYH4WM2NA2pY1W1VV7LNh4TAVTaD7mcJ7VcfaWK/mBXrJal6WZcIOW8ZRqBbHGdEMWa4o4iVwhlRVdU1UcjUNdV%2B4tW1C58QJCrdWJR7HXJCkKn1%2BYDT8WUHGwLDhBAd3NMAqA2qgSDNAcABUP2vYKc1MVOrHEepkk7muM17hD0bQ5WK4vlsIaMb5NpBAcyOmp2xWjdluWFRDS34xN0GkWhCxXRy25DvpZBGUQtm8TasgHM2NrzlTC3E%2BNECkeRQ5ofRXPajzdFCyLtLKUBjkaVwSz0Nwzb8AEvD8Og3AeLYtgCisazPNsfDkEQ2jy0sADWIBbFxWwABzSDIMizs2OK21sPBBIrXDSPwbAgM2WjkKrOjkBrXD8EoICBybXA6EscCwCg2DqHKPgGZQ1CvUoqjGLUIhIOgADuwf8BgbApAw6pZDnET0PnReq0bZcV4wCTAI75DNww8SROwGyl%2Bg5fd6QADyaf18X3BG8ncq3KQwCR%2BHwQp6gjSEKr/CCMIYgSJwMhyMIyhqJosd6AYRgmGg2vWIYBAxJHkBLOgKT1IvAC0I/I2/NA0Cwoxvw9IgSADhvwVB4EeqhgSQnVrKUgmUcAPxwuQPUwgCAcAACroG8IgpYSg9brBGEQdeNc84F0nmrY2/5OCB0Lu8FIU95aGCVirU2oduC4BXmnMgBx1C21nG/Wc0gDhvXlDIU8fkIBa2sLYG0%2BBiDcMNgsfgMc45LCQNgFgOAEhIK9j7cgfsqpB1YWHCOUdjam3jogCAKAVhEBSGnDOEAu6t17hwbgvD%2BGCOEagUR0hxH8GRPI%2BBBgt6iHEJIfeoSj4aFYfoTotCWD0LVgrZhRjT5sK4GPOxacDjoHhB4gRQi9jGD9DwW24jTxOUkYPFu8QNruyUeY0%2BlNyDqM0cMHR3A9EGPZiXDJpjo4WItoEHEp5pCzlthYW2OJmzNkSDiRIzZZyzi2EwrgWwWHpJMU0uO5AE4IHgPs6xaAanD0cc44YxSTBlJ4IHOg9AiDxEjhAGIrCYjhGaB8Bh5B3msFIB8EeMRdD6W%2BWXDgwgR5MHoF89JOAYg%2BGAB4CQ9BF5GxwA9EwkhYUEH/E4AgspF4hxnqgNOGwjZZVqKw8kMR3j/K8DgVhRBMp%2BwobAmI6RsAKmwBi4A5JL7NIEEYBeQ4CDYELiPFIzBvmhJ3hE2QUSVAxPSfoT2JSr7SJvtSnBocX5ZHfp/EBP8/5EAAeqJAMD4jwOwNqhw%2BkshuCYJ4bw7QDChCRHMYYnRCiZCEBMDoBR0g%2BqYLMIYCQpi1DtUIXo4xnWTC6JGhoYx%2BjutDYQvofq00tBDRUT1uD8F7xSVwZWaSQ5hx4XwwpBwrmlPKTwSpQU5EGXqTwRpKizatI0Vo6gwyA5rO6VbG21sh3DuHbOEt6tuADJ2Ywo5KALkUCoE405rc0AX3brbW5AgGCPNIM8156TfmfO%2BYe/5gLgVOFBYPcFRBIXQtYXChFSL6Aou%2BeikpWKQ6EFxc4AlrDiWku%2BRSr2IdqW0o%2BPSjYIcmVoO%2BWyjlXKeV8tAAKlULBhWivFZKxum95Cyr3vK%2BQ0ST4hziYYNV5gNV2C1fAJ%2BuqhD6q/ka/%2BgDgGgPAZA6BodYFWptRGvFrgIDuAzZ0N1ZRU1esDfUYTAaihZGzfMcN3Qo1Juk7a/jiaZgppzWG%2BwKnY3%2BumFmrTCm82rAIS2tZxa%2BlloKV46tvla31ogI2hRsIW3KKGR29p2ie2B10Zs0tk77BmLbS0r2Fhfb%2B0DtZoLoW9lWKsXO5d8RznJbbh3e5O691vI%2Bf849uWAVApBRQsFzAb1QphZ%2B7A8LEXItRfwN9mLIMNZxXa396T/2PMA8ISl6TQOfIg4y5lsH4jspUAh99voLGCrQ0oEVYqJVSooTK8J%2BGD6KEVcRs%2Bqy13qpsJqu%2B2rn6v24B/Rjv9mNmotXA1K1qaPxvUw6p1uR/WicGNpgw3qpP6c%2B5JuTxnPUPfqNG1oP3FMJpB/JwHhnQcvczcmsTH2LN4LMwWyzAWJ1cHLZ4oRIjfJ%2BIkS50gzbW2ectr2/z%2Biovjv6cFwZArZ0nKHq3VLzPhjtwdluh5TzqD7pDiemFRsBdnuK03K9ZXb2VYa9Vx9dXX3cvfc18gX62t3Y65wrrFCgNUrvmBwb6ToMsqNnB8bCvMVTZQ0KubGHFvYfW3hqQBHD6bdiSAWQu2KP7ao4d%2B7x29WnYNd/C7JqWMgLARAqBIhrs8fu2p%2BoT3pNvY9Tpr7WRpOp5KADnTceeh6bh%2BD9TkOs/w9U0mqHYbTP60WOjmnNmK1eLx2IwnhAm2KI880tRnaOm%2Bb7Rj2nkd6eqLWRFqnvaYtL1C8MxIWhTzNndokW50hpAWC0BYaQWx2Zew2bX2Lnnwt9%2B2ZP8gsCMiuGkEAA%3D%3D).

Here is an example with a simple `sv` vector class mimicking GLM (with a list of float instead of an array), and some  `VEC2SV`/`GLM2SV` inline functions that would be equivalent of  `VEC2GLM`/`GLM2VEC`:

```c++
#include <cstdio>
#include <array>

namespace sv
{
	using vec = float;
	struct vec3
	{
		vec x, y, z;
	};
};

using veca_t = float;
using vec3a_t = std::array<veca_t ,3>;

using vec_t = float;
using vec3_t = vec_t[3];

inline vec3a_t SV2AR(sv::vec3& v3)
{
	vec3a_t v3a;
	v3a[0] = v3.x;
	v3a[1] = v3.y;
	v3a[2] = v3.z;
	return v3a;
}

#define SV2VEC(v3) SV2AR(v3).data()

inline sv::vec3 VEC2SV(vec3_t& v3t)
{
	sv::vec3 v3;
	v3.x = v3t[0];
	v3.y = v3t[1];
	v3.z = v3t[2];
	return v3;
}

#define VectorSet( v, x, y, z ) ( ( v )[ 0 ] = ( x ), ( v )[ 1 ] = ( y ), ( v )[ 2 ] = ( z ) )

void print_v3(sv::vec3 v3)
{
	printf("%f, %f, %f\n", v3.x, v3.y, v3.z);
}

void print_v3t(vec3_t v3t)
{
	printf("%f, %f, %f\n", v3t[0], v3t[1], v3t[2]);
}

int main(int argc, char **argv)
{
	sv::vec3 v3;
	vec3a_t v3a;
	vec3_t v3t;

	v3 = { 1, 2, 3 };
	print_v3(v3);
	print_v3t(SV2VEC(v3));

	VectorSet( v3t, 4, 5, 6 );
	print_v3(VEC2SV(v3t));
	print_v3t(v3t);

	return 0;
}
```

**Comment by slipher** [comment]
Do you have some evidence that the current implementation of VEC2GLM is not optimized well? If so, please create a separate issue for that.

**Comment by illwieckz** [comment]
I'm not talking about `VEC2GLM` optimization but about a better implementation of `GLM2VEC` (the `&vec[0]` thing).

Our `VEC2GLM` implementation is basically the same as mine, just written in a better way, we already assume the compiler optimizes out the possible extra copies when converting in that direction.

```c++
inline glm::vec3 VEC2GLM( const T& v ) {
	return glm::vec3( v[0], v[1], v[2] );
}
```

I only implement both directions in my example for completeness. Implementating both directions is especially useful to test that the proposed implementation allows this (it doesn't):

```c++
	print_v3(VEC2SV(SV2VEC(v3)));
	print_v3t(SV2VEC(VEC2SV(v3t)));
```

It doesn't allow this and it's probably not a problem, but I wanted to test that.

I'm just saying that like we do a `VEC2GLM` that copies a `vec3_t` to a `glm::vec3`, we may have a `VEC2GLM` that copies a `glm::vec3` to a `vec3_t`, it seems to be doable. The `&vec[0]` is not only UB but also look like a way to avoid extra copies, but the compiler can very likely optimizes out the extra copies of an implementation that returns an copied array.

**Comment by slipher** [comment]
Not sure what you mean by "a better version of GLM2VEC" since we don't have any such function.

If we need to copy a `glm::vec3` to `vec3_t`, we can use `VectorSet`. Or if that somehow compiled inefficiently, `memset` would also work (but you'd need to be careful to use the size of the *destination*, since I believe enabling SSE can make the vector bigger).

**Comment by illwieckz** [comment]
Here is an example of `GLM2VEC` implementation:

```diff
diff --git a/src/shared/bg_public.h b/src/shared/bg_public.h
index 5add2d617..a23121c1f 100644
--- a/src/shared/bg_public.h
+++ b/src/shared/bg_public.h
@@ -42,6 +42,12 @@ inline glm::vec3 VEC2GLM( const T& v ) {
 DEPRECATED inline glm::vec3 VEC2GLM( glm::vec3 v ) {
 	return v;
 }
+inline std::array<float, 3> GLM2AR( glm::vec3 v ) {
+	std::array<float, 3> a = { v.x, v.y, v.z };
+	return a;
+}
+
+#define GLM2VEC(v) GLM2AR(v).data()
 
 #include "engine/qcommon/q_shared.h"
```

And here is an example of usage:

```diff
diff --git a/src/sgame/components/RocketpodComponent.cpp b/src/sgame/components/RocketpodComponent.cpp
index b72f58b6f..776aaf5f4 100644
--- a/src/sgame/components/RocketpodComponent.cpp
+++ b/src/sgame/components/RocketpodComponent.cpp
@@ -209,7 +209,7 @@ bool RocketpodComponent::SafeShot(int passEntityNumber, const glm::vec3& origin,
 	glm::vec3 end  = origin + ROCKETPOD_RANGE * direction;
 
 	trace_t trace;
-	trap_Trace( &trace, &origin[0], &mins[0], &maxs[0], &end[0], passEntityNumber, MASK_SHOT, 0 );
+	trap_Trace( &trace, GLM2VEC(origin), GLM2VEC(mins), GLM2VEC(maxs), GLM2VEC(end), passEntityNumber, MASK_SHOT, 0 );
 
 	// TODO: Refactor area damage (testing) helpers.
 	return !G_RadiusDamage(
```

This is in replacement of `&vec[0]` which is our currently (not named and impossible to grep) `GLM2VEC`.

It works on my end.

**Comment by slipher** [comment]
We shall learn how to grep, with `clang-query`. First, prepare the compilation database:

```
cd Unvanquished
cmake -B build/compdb -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXPORT_COMPILE_COMMANDS=1
# you don't need to actually build anything, except the CBSE target if generated stuff is missing
``` 

Now, query for the GLM vector abuse.
```
find src -name '*.cpp' | xargs -n1 -P6 -- clang-query -p build/compdb {} \
-c 'm unaryOperator(hasOperatorName("&"), hasDescendant(cxxOperatorCallExpr(hasOverloadedOperatorName("[]"),
hasDescendant(expr(hasType(hasDeclaration(typedefNameDecl(hasName("vec3")))))))))' \
2>/dev/null | grep -vE 'matches[.]$'
```

Results attached [spam.txt](https://github.com/user-attachments/files/15517244/spam.txt)
