### ISSUE TITLE
Some glass texture in perseus is not lit

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#3161]
See the glass texture on the doors:

![unvanquished_2024-10-27_020023_000](https://github.com/user-attachments/assets/2296fe2e-cfb8-4516-8483-bba04028cbce)

At first I wondered if that was an overbright bug, but in fact the glass texture looks like it is fullbright, not receiving shadows and then, not light.

I don't know yet if it's a renderer bug or a map compiler bug.

This is the material:

```
textures/perseus_custom/glass_02
{
	qer_editorImage textures/perseus_custom_src/scratchglass_d

	surfaceparm nomarks
	surfaceparm trans

	{
		map textures/perseus_custom_src/scratchglass_d
		blendfunc add
		rgbGen const ( .1 .1 .1 )
	}
	{
		map $lightmap
		blendfunc gl_dst_color gl_src_alpha
		rgbGen identity
		tcGen lightmap
	}
}
```

The engine lists the two stages:

```
------------------------------------------------------------------------------------------- 
num   shaderType shaderSort     stageType              interactLight stageNumber:shaderName 
------------------------------------------------------------------------------------------- 
230   3D_STATIC  BLEND0         COLORMAP               INTERACTLIGHT 0:textures/perseus_custom/glass_02 
230   3D_STATIC  BLEND0         LIGHTMAP               INTERACTLIGHT 1:textures/perseus_custom/glass_02 
```

**Comment by slipher** [comment]
I don't think lightmapping a translucent surface is even possible? A lightmap stage relies on the depth buffer to test whether the shader is being drawn in that pixel or not. But translucent surfaces don't write to the depth buffer. Even if they did, we wouldn't know what the texture color is supposed to be because what's in the color buffer is a result of blending.

**Comment by VReaperV** [comment]
> I don't think lightmapping a translucent surface is even possible? A lightmap stage relies on the depth buffer to test whether the shader is being drawn in that pixel or not. But translucent surfaces don't write to the depth buffer. Even if they did, we wouldn't know what the texture color is supposed to be because what's in the color buffer is a result of blending.

Lightmapping does work with translucents. The fragments that are in front of anything opaque are drawn, others aren't. I haven't looked at how q3map2 handles lightmaps for semi-transparent surfaces though.

**Comment by VReaperV** [comment]
> At first I wondered if that was an overbright bug, but in fact the glass texture looks like it is fullbright, not receiving shadows and then, not light.

Maybe we should have a command to display shader info for wherever surface you're looking at. Right now I have to use a combination of frame debugger, VS debugger with hacky if statements and breakpoints, and looking at shader files, for issues like this.

**Comment by slipher** [comment]
> Lightmapping does work with translucents. The fragments that are in front of anything opaque are drawn, others aren't.

Then how does the lightmap know what the color to multiply with the lightmap color should be?

Is there an example of a working lightmap with a translucent surface?

**Comment by VReaperV** [comment]
> Then how does the lightmap know what the color to multiply with the lightmap color should be?

The colour of the surface? Why would it multiply the lightmap with anything else?

> Is there an example of a working lightmap with a translucent surface?

Doors on moonbase, glass on pulse.

**Comment by VReaperV** [comment]
I've checked the door on perseus, the first stage ends up being a Generic3D with inverse light factor set to 1.0, while the second stage is lightmapped, with inverse light factor -0.25.

**Comment by VReaperV** [comment]
So the reason here is that because there's a lightmap stage this gets set to `false`:
https://github.com/DaemonEngine/Daemon/blob/a96b2a1163d39a3587b23fed166693dc22f5924b/src/engine/renderer/tr_shader.cpp#L5249
Then when rendering, inverse light factor gets set to -0.25 (with default settings) for the lightmapping stage at https://github.com/DaemonEngine/Daemon/blob/a96b2a1163d39a3587b23fed166693dc22f5924b/src/engine/renderer/tr_shade.cpp#L1132 but to 1.0 for the generic stage at https://github.com/DaemonEngine/Daemon/blob/a96b2a1163d39a3587b23fed166693dc22f5924b/src/engine/renderer/tr_shade.cpp#L925
I don't know what behaviour is supposed to be correct here, but this should be enough information to decide that.

**Comment by slipher** [comment]
> The colour of the surface? Why would it multiply the lightmap with anything else?

I don't think the lightmap shader knows this.

I downloaded a `map-moonbase_0.7.1.dpk` and the doors are using this. There is no lightmap stage.
```
textures/moonbase_glass/glass1
{
	qer_editorimage textures/moonbase_glass/glass1
	surfaceparm trans
	cull none
	qer_trans 0.5
	{
		diffuseMap textures/moonbase_glass/glass1
		blendfunc blend
		alphagen const 0.4
	}
}
```

**Comment by illwieckz** [comment]
Here:

`
		diffuseMap textures/moonbase_glass/glass1
`

It means a light map is applied on `textures/moonbase_glass/glass1`.

**Comment by VReaperV** [comment]
> I don't think the lightmap shader knows this.

Knows what?

> I downloaded a `map-moonbase_0.7.1.dpk` and the doors are using this. There is no lightmap stage.

It still uses the lightmapping shader.

**Comment by slipher** [comment]
Thanks. So the moonbase glass works because it has a lightmap that is done together with the diffusemap in a single stage. The Perseus glass on the other hand actually has 2 separate stages according to `listshaders`. So in that case maybe the concerns about the lightmap shader not knowing the diffuse color are valid?

**Comment by slipher** [comment]
The `blendfunc gl_dst_color gl_src_alpha` in the lightmap stage doesn't make any sense. I assume lightmaps don't have alpha, so it would be equivalent to `GL_DST_COLOR GL_ONE`. In other words we are doing red = (lightmap red * framebuffer red) + framebuffer red, and so on for each component. This makes the stuff behind the glass brighter, instead of darker as it should be. (Well the first stage also does that since it is using `blendfunc add`... but the 2nd stage is worse.) You can easily see this with `/testshader textures/perseus_custom/glass_02`.

![unvanquished_2024-10-28_075459_000](https://github.com/user-attachments/assets/564240d9-86d6-4170-9a06-ec12c8d30a89)

Also the glass texture in the screenshot looks a lot worse with full-range overbright. With clamping you couldn't tell that it's wrong unless you looked closely.

The texture could be fixed by using the `diffusemap` keyword to get the collapsed stage with correct lightmapping. I maintain that it is impossible to do mathematically correct lightmapping of a translucent texture as a true separate stage.

**Comment by VReaperV** [comment]
Should we consider this a map bug then?

**Comment by illwieckz** [comment]
> > The colour of the surface? Why would it multiply the lightmap with anything else?
> 
> I don't think the lightmap shader knows this.

The lightmap shader doesn't need to know about it. The texture state is rendered then the lightmap stage is renderer and the two stages are blended (not in a shader).

**Comment by slipher** [comment]
> The texture state is rendered then the lightmap stage is renderer and the two stages are blended (not in a shader).

I don't think there's anything like "blending two stages together". Each stage operates directly on the color/depth buffers. This is not a fancy Photoshop with layers; it's MS Paint where what you see is all you've got. So a lightmap in a separate stage can only achieve the correct result for an opaque surface, where you can assume the color buffer is the same as the diffuse texture. Otherwise you don't know what the diffuse color was.

**Comment by illwieckz** [comment]
You don't have to know the what was the color, only to know how the current stage is blended over the current color buffer. writing a new transparent surface above another surface isn't that different to blend a stage above another stage for the same surface.

**Comment by slipher** [comment]
To make sure we're on the same page here, I'm assuming that the desired result for lightmap + translucent alpha blending is `alpha * lightmap color * diffuse color + (1 - alpha) * buffer color`. 

If you try to multiply the lightmap color with something from the buffer, it will get mixed with stuff behind the glass.

**Comment by illwieckz** [comment]
> If you try to multiply the lightmap color with something from the buffer, it will get mixed with stuff behind the glass.

This is wanted if the glass is using an `add` operation, which is done there. The result of the lit glass color is expected to be added to the background.

**Comment by slipher** [comment]
The `add` operation doesn't really make sense there. There's no reason why the glass should be glowing with its own light. But OK, it's not so bad since failing to multiply the background by 0.9 is not especially noticeable.

The second stage is a complete disaster because it multiplies the lightmap with the color buffer at full strength. The lightmap is supposed to multiply with the glass's color, but the color buffer is almost all background and only a tiny bit of glass. With lightmap values greater than 1 from full-range overbright, the result is primarily amplifying the brightness of everything in the background.

Without collapsed shaders, I guess the best thing you could achieve is to model the glass diffuse as a constant color, like this Pulse glass shader. Here it does seem sensible for the lightmap stage to use `add`. Though I still don't see why the diffuse doesn't use blend.
```
textures/pulse/plexiglass
{
	qer_editorimage textures/pulse/plexiglass.tga
	qer_trans .5
	
	surfaceparm trans
//	surfaceparm lightfilter
	cull none

	{
		map $lightmap
		tcGen lightmap 
		blendFunc add
		rgbGen const ( 0.1 0.1 0.1 )
	}
	{
		map textures/pulse/plexiglass.tga
		tcGen environment
		blendFunc add
		tcmod scale 1 1
		rgbGen const ( 0.05 0.05 0.1 )
	}
}
```

**Comment by illwieckz** [comment]
I don't really mind if that's correct to add a texture to a lightmap instead of multiplying them (of cours it is not correct), the new overbright implementation should not multiply what was not.

**Comment by illwieckz** [comment]
I have a fix anyway:

- https://github.com/DaemonEngine/Daemon/pull/1404

**Comment by illwieckz** [comment]
The bug would have likely affected the same kind of shader with two added colormaps even if the first one was not a lightmap.

**Comment by illwieckz** [comment]
This is a bug similar to the one we faced with decals: an translucent surfaces in front of another surface is like a stage in front of a stage.
