### ISSUE TITLE
Performance decreased since Alpha 29 (libRocket)

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#342]
Some players have reported notably decreased performance since Alpha 29. My own framerate was previously around its upper limit of 125 fps and is now stuck around 90. The libRocket code should be profiled to find out potential performance bottlenecks.

**Comment by Viech** [comment]
@DolceTriade can you close or comment on this issue? I'm pretty sure there must have been significant performance improvments since then.

**Comment by Kangz** [comment]
I think this is a constant work in progress but has been improved a lot so I'd close it.

**Comment by DolceTriade** [comment]
WIP. I'd wait until librocket is moved to the cgame to close completely.

**Comment by illwieckz** [comment]
The main menu was rendered even when hidden:

- https://github.com/Unvanquished/Unvanquished/issues/1318 - _Unvanquished framerate multiple time lower than raw engine framerate because of the menu being rendered when hidden_
- https://github.com/Unvanquished/Unvanquished/pull/1319 - _do not render the menu when hidden_

libRocket is still too much slow.

It is expecte to be replaced with RmlUi that fixes bugs ( https://github.com/Unvanquished/Unvanquished/issues/1152 ) and may also bring more performance optimizations. See https://github.com/Unvanquished/Unvanquished/issues/1200 for progress on RmlUi side.
