### ISSUE TITLE
<dataselect source="x"/>  drop-down boxes do not have anything selected by default

### ISSUE THREAD

**Issue by Veyrdite** [Unvanquished/Unvanquished#369]
## Overview

Currently:  Drop-down boxes that don't have their options "pre-determined" in the .RML are empty by default:

![emptymenu_audio](https://cloud.githubusercontent.com/assets/6168874/3748584/136d57e6-17df-11e4-9820-824dc1d4f158.png)

Expected behavior: a default (first?) option is selected by default.

**Comment by bmorel** [comment]
This is still true, but I only seen it in 2 cases: the sound screenshot above, and the map selection UI.
It does *not* appear for the graphical settings, so this looks more like a specific issue with the "openAl Device" list than with rocket or cvars to me.

**Comment by necessarily-equal** [comment]
I think that this issue is solved: it only appears in case the value of the cvar isn't a value in the dropdown.

In the openAL device case, this is because you are likely not to have any openAL device. In the map selection list, it is probably that no default map is chosen.

I'm closing this, please open individual issues if you think an empty selector is a problem.
