### ISSUE TITLE
OSX crashes various

### ISSUE THREAD

**Issue by TimeStop12** [Unvanquished/Unvanquished#476]
A bit of a hard one as there is no crash log for what has happened. 

OSX can crash when adjusting options, as well as crash when joining a server.

Visual effects are black screen when applying options and then ctd. As well as server saying connecting and the ctd as well. No error logs unfortunately.

**Comment by zamber** [comment]
Hi,
I've been having problems with connecting to a game. As this issue is pretty much dead I will just hijack it :).

Mac OS X 10.10.3
MacBook Pro (Retina, 15-inch, Late 2013)
GeForce GT 750M 2048 MB
Log: http://pastebin.com/HH6RJzU7

```
Error Opening file /Users/cwallez/personal/Unvanquished/external_deps/build-macosx64-3/prefix/share/GeoIP/GeoIPv6.dat
Error: CGame VM: IPC: Unexpected end of message
```

Running from source. Initially compiled myself and got same behavior as with a build provided later by `Ishq (~modi). 0.38.0.

**Comment by harmonise** [comment]
Bug is over a year old. I'm closing. @zamber if you're still experiencing any issues please feel free to open a new issue.

**Comment by zamber** [comment]
Sure, go ahead. I went to IRC. We debugged and fixed it there. It was introduced by some merge that went a bit wrong :).
