### ISSUE TITLE
You can't sell grenade if you don't have the credit to buy it.

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#518]
For example, you have 237$, you buy a fire grenade 200$, you have 37$, you cannot resell the fire grenade unless you get at least 200$ to buy a new one.

So, to buy and resell a 200$ fire grenade, you need 400$.

There is a similar bug in buildings: You have 8bp, you can build 1 turret with 10 bp, and you can replace 1 turret with 0bp, since 0+10 = 10.

But you can't replace a building turret (before build completed) if you don't have 10 bp.
So if you have 10 bp, you can build a turret, wait the build end, replace the turret.
If you have 20bp, you can build a turret, and while the turret is building, replace this turret.

**Comment by DolceTriade** [comment]
I see. Interesting, I thought I handled the buy part in the code. Will take a look.

**Comment by Viech** [comment]
The buildable part is no bug but intentional: While buildables are being constructed, their (build point) value increases (just like their health). This also means that a buildable that is killed right after its placement will give the enemy team fewer momentum than it would give after construction finished, as momentum gain is bound to build point value (with the exception of OM/RC that use a fixed value).

Assigning @DolceTriade for the other part.
