### ISSUE TITLE
Optimize the server side gamelogic

### ISSUE THREAD

**Issue by Viech** [Unvanquished/Unvanquished#526]
@illwieckz reported that his server had performance problems, which lead to noticable lags during gameplay. Sometimes the lags are periodic (e.g. all five seconds).

This issue is about optimizing the server side gamelogic itself. Ultimately, some things need to be fixed on engine and gamelogic backend level:
* Using CBSE, think functions should be scheduled. Right now a lot of them are triggered in the same frame since they use a multiple of 1000 ms as a think timer.
* Using CBSE, entity iterations can be limited to relevant entities only. Right now we iterate over all entities a lot, even if most of them are irrlevenat due to their type.
* Traces and other former trap calls that are frequently used in the gamelogic should be computed inside the gamelogic as opposed to inside the engine. The latter is known to produce delays.

**Comment by illwieckz** [comment]
I had not noticed performance problem on 0.34.0 [even with many people at dev game time](http://forums.unvanquished.net/viewtopic.php?f=62&t=1698).

Two things have change:
* I served 0.34.0 with deb package, I server 0.35.1 with universal zip.
* 0.35.1 have rocket pods.

The best map to experience lag is perseus with bots and rocket pods, the `nacl_helper_bootstrap` process can take more than 100%CPU.

**Comment by illwieckz** [comment]
With  +set vm.game.type 4 (solib instead of nacl) it runs better, but experiences lag with rocket pods too (but later, needs more rocket pods to lag).

**Comment by illwieckz** [comment]
The performance issue seems to be map-related, since in the same map I can spawn 40 rocket pod in one place and run as dretch under fire in front of them without lag, and in another place of the same map during the same game on the same server, I experience lag with only 6 rocket pods (and some people have noticed lag with only 2 rocket pods before the rocket pod update and your gamelogic optimizations).

No lag:
![no lag](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/shots/unvanquished_2015-01-25_044410_000.jpg)

Running as dretch under fire in front of 40 rocket pods on my dedicated server and staying alive (demo):
[unv035git.perseus-rocket-dodge-in-hell.1-dretch-versus-40-rocket-pods.dm_86](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/demos/unv035git.perseus-rocket-dodge-in-hell.1-dretch-versus-40-rocket-pods.dm_86)

Lag:
![lag](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/shots/unvanquished_2015-01-25_035209_000.jpg)

Also, I can put on knees a powerful 4GHz 8 core CPU putting rocket pods in this place of this map (and still not lag on the other place), so if my server is not powerful like this one, I know it's not my server fault : I experience the same problem with an high end computer which is high above the hardware requirements.

This performance issue is not related to player or bot too, only one bot or only one player in front of some rocket pod in the bad place is sufficient to lags the server. Having multiple bots and player on server just increase normally the average usage, so problems come faster.

**Comment by Viech** [comment]
I briefly profiled the server side gamelogic and tried to improve the performance impact of human defense structures in 90d554e. I'm afraid there's not much significant I can do without affecting the logic. The rest is up to CBSE and low-level improvements as outlined above.

**Comment by illwieckz** [comment]
Thanks, I will try that right now. :smile:

**Comment by Viech** [comment]
As far as I remember, you're already running these changes. I put them on the `devserver` branch for you a while ago.

**Comment by illwieckz** [comment]
Ah OK, it was that. So, it's 100% sure now: my server is running these changes. :smiley:
