### ISSUE TITLE
"Server Shutdown" because "Too many open files" then "Bad file descriptor"

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#532]
Hi, right now on my server, Enbaldur joined the game, voted for a draw, then Unvanquished prints that:

```
Failed to open 'game/games.log' for appending: Too many open files
WARNING: Couldn't open logfile: games.log
Failed to open 'game/stats/gameplay/20150124_020704_parpax.log' for writing: Too many open files
WARNING: Couldn't open gameplay statistics logfile: stats/gameplay/20150124_020704_parpax.log
```

then:

```
^8IPC: Failed to map shared memory object of size 4063232: Bad file descriptor
----- Server Shutdown -----
```

See `daemon.log`: http://pastebin.com/SqFcrsSf

**Comment by Amanieu** [comment]
You shouldn't be using the .so file in production, it is only meant for debugging. Prefer use the exe or nacl VMs instead.

The problem here seems to be that the filesystem files are not closed when the shared library is unloaded, which leads to you running out of file descriptors. I'll try to fix this, but this is one of the reasons why you shouldn't use the .so VM on production servers.
