### ISSUE TITLE
Forlorn AI bugs

### ISSUE THREAD

**Issue by Sherif89** [Unvanquished/Unvanquished#542]
I played on Forlorn in server gg.illwieckz.net { le frag courtois }. The alien AI acted strangely:
1.  It goes and comes back at the high area of the alien base, where there were barricades and eggs.
![ai bug2](https://cloud.githubusercontent.com/assets/8778976/5926527/648745c8-a674-11e4-8576-64853da612ca.png)
2. Dretches (And maybe mantis and marauders) may try to go through the wall.
![ai bug](https://cloud.githubusercontent.com/assets/8778976/5926620/14ee5c30-a675-11e4-91f6-94fc3ec567d6.png)
3. I don't know if it was programmed to do this. I tried to attack a marauder, trying to go through a wall, while I was an advanced marauder then I was killed quickly. I suspect who killed me was an advanced marauder as there were a one behind me.
4. If I'm a granger and a dragon sees me, it kills me. It happened many times. If I run, it chases me till I'm cornered by the wall then kills me.
5. If I try to build an egg, an acid tube and a leech at a place, not too far from the base, some alien destroys them. I didn't try to build on other places.
Most of the dragon attacks were at this place. Sorry, I can't describe it accurately.

Note: I've the map, but an about 8 MB file was downloaded. (Sorry, I don't remember its name). Maybe it's a little different map?

**Comment by Viech** [comment]
1. This is a known incompleteness in the bot code. Bots don't jump down (on their own) or wallclimb up.
2. I assume the nav meshes have been generated for another version of this map. Can you name the exact version of the map pk3 you are loading? Use the `listPaths` command.
3. + 4. + 5. Are you sure this was a bot and not a player who killed you? Bots would never attack a teammate on purpose.

**Comment by illwieckz** [comment]
Hi @Sherif89 !

> Note: I've the map, but an about 8 MB file was downloaded. (Sorry, I don't remember its name).
> Maybe it's a little different map?

If you connect to my server with a bare 0.35 Unvanquished, downloaded files are:

* `map-forlorn_a10+1.pk3` : an update to forlorn from EmperorJack (the mapper)
* `mod-devserver_2015-01-18-1907-viech.pk3` : cgame update from @Viech 
* `rocketpod_2015-01-11-1600-viech.pk3` rocket pod update from @Viech
* `spiker_2015-01-18-1855-viech.pk3` spiker addition from @Viech 

So it's mainly backports from next 0.36.0, and yes the map is a little different one.

There is a similar bugs in one room of Spacetracks (I have screenshots too).

**Comment by illwieckz** [comment]
@Sherif89 can you give me your in-game name? With your name I can find in log if it's a bot or a player that killed you.

@Viech:
These are screenshots of similar bot bugs I’ve seen this morning on “Spacetracks” map (on Training server).

4 bots are stuck at the same place, on the floor, like if they try to go somewhere right vertically below or above them:
![4 bot stuck on the floor](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-28_025710_000.jpg)

Bot stuck in wall:
![bot stuck in wall](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-28_025732_000.jpg)

In fact, they unstuck while they evolve, and they unstuck if they see a human in order to chase it. It seems to not be a navmesh issue, they know where they can walk and where they can't, but it seems they try to go somewhere they can't (perhaps on the roof or on the floor).

If I push a stuck bot, it comes back to get stuck in the same place:
![bot want to be stuck](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-01-28_025946_001.jpg)

It's not they *can't* go elsewhere, they *want* to go there.

**Comment by Viech** [comment]
I'm not sure if these qualify as bugs given that the bot code was never really finished by @cmf028.

**Comment by Sherif89** [comment]
Output of listPaths:
````
Home path: /home/My_Account/.unvanquished
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.35.1.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.35.0.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.34.0.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.33.0.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.32.0.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.31.0.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.30.0.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.29.0.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.28.0.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.27.0.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.26.0.pk3
Loaded pak: /home/My_Account/Downloads/unvanquished_0.35.1/pkg/unvanquished_0.25.0.pk3
````

>+ 4. + 5. Are you sure this was a bot and not a player who killed you? Bots would never attack a >teammate on purpose.

>@Sherif89: can you give me your in-game name? With your name I can find in log if it's a bot or a >player that killed you.
I'm not sure. My name was **Sh**.

**Comment by illwieckz** [comment]
> Output of listPaths:

It seems to be the `listPaths` you get when you run Unvanquished from scratch, not while you are connected to my server (since your screenshots seems OK I assume the extra packs were successfully loaded :wink: )

I confirm that your Unvanquished client had downloaded the map update from my server:

```
Redirecting client 'Sh' to gg.illwieckz.net/dl/unvanquished/pkg/map-forlorn_a10+1.pk3
```

It seems you already have the backports (probably from Dev or Training server).

> I'm not sure, if I'm killed by a player. My name was Sh.

OK, at `2015-01-27 19:45:33 Z` there was a game on forlorn with 6 bots and 4 players including you, and a player teamkilled you 4 time and warned you about building.

```
  5:59 Die: 10 8 MOD_LEVEL3_CLAW: ******** killed Sh
  6:04 SayTeam: 10 "********": don't build
  6:08 Die: 10 8 MOD_LEVEL3_CLAW: ******** killed Sh
 10:16 Die: 10 8 MOD_LEVEL3_CLAW: ******** killed Sh
  6:38 SayTeam: 8 "Sh": The AI of a dragon is smashing the worker of its side!!!!!!!!!!
  6:48 SayTeam: 8 "Sh": It killed me 2 times.
 15:59 SayTeam: 10 "********": stop fing building
 26:51 Deconstruct: 8 202 leech MOD_LEVEL2_CLAW: Leech destroyed by Sh
 26:56 Die: 10 8 MOD_LEVEL2_CLAW: ******** killed Sh
 27:22 SayTeam: 10 "********": you can deconstruct buildings
 27:27 SayTeam: 10 "********": never destroy
 27:28 SayTeam: 8 "Sh": The dragon is crashing me.
```

So, it seems he was angry because he did not like the way you build and because you destroyed building instead of deconstructed (doing this loses build point that can't be recovered).

So it's not fair to teamkill, but beware to understand how the game works and to read messages from others.

For example, never destroy building (it loses definitively build point that could be hard to mine), and prefer to replace buildings instead of deconstruct them (unless they are too vulnerable) be cause it can penalize your team. :stuck_out_tongue_winking_eye: 

So, it's sure: it was not a bot who teamkilled you. Sometimes bots can teamkill accidentally (stray bullet), but never intentionally, even if you attack them. So, it's not fair, but if a member of your team teamkills you intentionally, this is definitely it has something to tell you and tries to get your attention.

However, I hope that this incident will not deter you to play Unvanquished, and I hope to play with you soon. :sweat_smile:

**Comment by Viech** [comment]
There's another issue about bots having navigation problems (#310) and any navmesh mismatch will be fixed with the next alpha release of Forlorn. All other bullet points were resolved by @illwieckz, therefor I'm closing this.

**Comment by Sherif89** [comment]
>So, it seems he was angry because he did not like the way you build and because you destroyed building instead of deconstructed (doing this loses build point that can't be recovered).

So it's not fair to teamkill, but beware to understand how the game works and to read messages from others.
>

My places were strategical. :smiley_cat: 

>For example, never destroy building (it loses definitively build point that could be hard to mine), and prefer to replace buildings instead of deconstruct them (unless they are too vulnerable) be cause it can penalize your team. 
>

I'll look how to do it.

>However, I hope that this incident will not deter you to play Unvanquished, and I hope to play with you soon.
>

I like Unvanquished and I'm waiting new releases.
