### ISSUE TITLE
How many spawns left: can't count

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#561]
often, I'll build lots of spawns, because they're dead sexy.
Then when I die, i see the message that I'm in the queue, but there's only 2 spawns left.

I freak out thinking my base has been killed!1!

But no, the spawns left thingy can't count right.

**Comment by Viech** [comment]
@DolceTriade could you confirm this?

@overvolting, please try to use a more formal and precise tone when writing issue reports. :wink:

**Comment by lamefun** [comment]
Happens for me too.

**Comment by illwieckz** [comment]
Yes, it happens to me every days since some months

**Comment by illwieckz** [comment]
I build 3 eggs (and remove all the others):

![3 eggs built](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-05_084510_000.jpg)

Then I die, Unvanquished says to me there is 3 eggs left:

![3 eggs left](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-05_084547_000.jpg)

Then I kill an egg as human:

![killing egg](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-05_084727_000.jpg)

Then I try to spawn as alien:

![two eggs left](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-05_084755_000.jpg)

Unvanquished says there is 3 eggs remaining instead of two.

In real game in real life, the most common case is less eggs than real (And I think I got one time "no spawn but there was spawn).

Then I build two more eggs (4 eggs) then die:

![4 eggs left](http://dl.illwieckz.net/u/thomas-debesse/bazar/unvanquished/bugs/unvanquished_2015-02-05_085423_000.jpg)

Unvanquished says there is 2 eggs left.

**Comment by Viech** [comment]
I'm merging #567, where @illwieckz reported that the "spawns remaining" text isn't cleared when joining spectators from the spawn queue.

**Comment by DolceTriade** [comment]
https://github.com/Unvanquished/Unvanquished/commit/ac7c9053175bf3bb7ca98fd671392cbc9ddfd5ab

This might have fixed the issue. Please let me know if this still happens.

**Comment by Viech** [comment]
Doesn't seem to work with translation atleast. I see the `%d` in the translated string.

**Comment by DolceTriade** [comment]
You mean you literally see "%d"?

**Comment by Viech** [comment]
Yes.

**Comment by DolceTriade** [comment]
Still happen?

**Comment by Viech** [comment]
The `%d`? Yes, on current master of a3794f9. You should be able to reproduce if you set the translation to german.
