### ISSUE TITLE
Unvanquished crash when it is the selection of genre

### ISSUE THREAD

**Issue by Horizon93** [Unvanquished/Unvanquished#581]
Sometimes when my character dies and to reappear we must select the type (construction kit or soldier kit) the game crashes.
But not every time, but it's a shame that after 30 minutes of games, I die and I have to reappear, the crash games. thank you :) !

**Comment by Viech** [comment]
@Horizon93 do you know how to create a backtrace of the crash? Do you get any error message (`crashlog.txt`)? It sounds hard to reproduce. It would help if we knew whether this was a problem with the UI, gamelogic or engine.

**Comment by Horizon93** [comment]
@Viech There just a dialog box that say "Unvanquished stopped working." After some research, I solve the problem, my game file was not in "My games" with some other folder. I think it was missing files that caused this crash. But thank you for your support.

**Comment by Viech** [comment]
If a mandatory file was missing, there should've been an error message about this instead of a crash. Can you tell the name of the file that you think was missing?

**Comment by Horizon93** [comment]
To be precise, it is a mistake on my part, because I had not put the win64 folder (with the pkg file) in "My Game" where to find the config file and game and GLSL. I do not know if it was exactly the source of the problem, but now the game does not crash. Thanks.
(Your map is awesome, good work! Just a question, what software you use for map making, Quark, GTKRadient, please tell me, thanks again)

**Comment by Viech** [comment]
@Horizon93 thank you! Me and as far as I know also EmperorJack (plat23, thunder, forlorn) and Pevel (perseus, yocto, antares) use NetRadiant. Not sure about Supertanker (station15, spacetracks, chasm). Thanks to @neumond there's also good support for GTKRadiant. You can find Unvanquished packages for both editors [here](https://github.com/Unvanquished/mapeditor-support)

Going to close this, even though it's still a verbosity-type issue as there was no proper error reporting about the missing resources. However, without precise knowledge about what file was missing this issue is too generic.
