### ISSUE TITLE
Debian launcher use deprecated paths

### ISSUE THREAD

**Issue by illwieckz** [Unvanquished/Unvanquished#665]
As you can see [here](https://github.com/Unvanquished/Unvanquished/blob/ef3823ab8c391101f808dfec619aa425ac3ef15f/debian/scripts/unvanquished#L10), the Debian launcher use deprecated paths:

```sh
UNVPIPE=~/.Unvanquished/main/pipe
```

Both `~/.Unvanquished` and `$homedir/main` are deprecated.

_Edit:_ And the pipe is now called `svpipe`.

**Comment by Viech** [comment]
Only thing we can do is ping @dsalt and hope he's well and alive. Closing this since we can't afford to collect distribution issues outside the developers control here, rather report to Debian if Darren doesn't react.

In the long run we need a wiki page that explains precisely how to package our releases.
