### ISSUE TITLE
Potential memory leak in pubkeys

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#675]
jkent | `Ishq: i think i found an issue in unvanquished on its use of rsa_public_key_init and rsa_private_key_init -- these functions call mpz_init internally which allocate memory.. there are no            corresponding rsa_public_key_clear and rsa_private_key_clear calls.. this happens in CL_LoadRSAKeys every time a new connection is made                                                                │

jkent | tl;dr: alloc() without free()    

citation: https://gmplib.org/manual/Variable-Conventions.html

**Comment by Viech** [comment]
@jkent Can you maybe provide a fix for this or more detailed instructions on how to fix?

**Comment by jkent** [comment]
Addition to cl_main.cpp:

```c++
static void CL_UnloadRSAKeys( void )
{
	rsa_public_key_clear( &public_key );
	rsa_private_key_clear( &private_key );
}
```

With the current implementation, I'm not sure where it should be called without a possible free without alloc.  Also since [CL_LoadRSAKeys is called while CA_CHALLENGING] (https://github.com/Unvanquished/Unvanquished/blob/7702b727c66898d66cf15d455a96f607fdd02975/src/engine/client/cl_main.cpp#L2628), every connect packet resend will cause the keys to be loaded again.  In my tremulous pubkey code, I'm loading RSA keys in CL_Init, and cleaning up in CL_Shutdown.

It might also be a good idea to [zero the memory used by libgmp] (http://grangerlab.grangerhub.com/jkent/tremulous-1-1/blob/8c25949e10d806ab5fc7aeba7f698e9d6e11a5a2/src/qcommon/crypto.c), so the private key doesn't persist in memory.  I'm hoping to take it a step further;  I'm waiting on Akamai to relicense [some secure buddy allocator code] (http://article.gmane.org/gmane.comp.encryption.openssl.devel/24356) from the openssl license to GPL2+ so I can protect libgmp memory with guard pages and keep the keys out of core dumps.

Feel free to message me (jkent) on Freenode.

**Comment by Viech** [comment]
Thank you! @Kangz or @Amanieu, can one of you handle this?

**Comment by Amanieu** [comment]
Can't we just load the keys once on startup and leave them loaded for the whole duration of the program?

**Comment by Kangz** [comment]
That seems sensible
