### ISSUE TITLE
Short, reproducible freezes on certain events.

### ISSUE THREAD

**Issue by overvolting** [Unvanquished/Unvanquished#705]
I've been getting short freezes in 0.38. 
One always happens at the end of map loading.
One always happens when I see first buildable.
One always happens when I see first enemy.
One always happens when I see first shooting.

Then after the initial freezing, they do still happen sometimes, but I can't determine why and they're less frequent.

**Comment by Viech** [comment]
Did this not happen before? This looks like the average memory shortage that leads to swapping of resources. Try disabling `r_lazyShaders` if it's enabled for you. If this is freshly itnroduced it sounds like something @gimhael should have a look at.

**Comment by overvolting** [comment]
It's never happened before, it's new to 0.38 and i've seen several people reporting it in game.

**Comment by DolceTriade** [comment]
I can reproduce this locally. Will look into it.

**Comment by DolceTriade** [comment]
Hm, the pauses seem more random and not consistently reproducible. Also, probably nothing to do with fileloading.

**Comment by overvolting** [comment]
They seem reproducible to me at the start of the game, then they become random.

When loading the same map 'veddak' and starting in the same spawn with the same layout, the lags came at the same points in initial map exploration.

**Comment by guillaume-uH57J9** [comment]
Hi, same issue here,

How can I permanently disable r_lazyShaders ?

There are some variables within ~/.unvanquished/config; but the comment says the file is generated and should not be manually modified. 

System : Intel Graphics, Debian GNU/Linux;

**Comment by Viech** [comment]
@guillaume-uH57J9 does disabling `r_lazyShaders` fix it for you? You should be able to disable it permanently if you write `seta r_lazyShaders 0` or just `r_lazyShaders 0` in the ingame console. Only `set r_lazyShaders 0` would change it temporarly. (Otherwise we have another bug. Also yes the temporary/permanent distinction syntax is beyond unintuitive.)

**Comment by guillaume-uH57J9** [comment]
@Viech yes, it does work.

Rendering feel much smoother after adding the option to autogen.cfg; and frame drops comes back at the next start (ie afte autogen.cfg get overwritten)

Thanks for the instructions for enabling it permanently.

**Comment by Viech** [comment]
I wonder why `r_lazyShaders` would be enabled for people who didn't set it manually.

**Comment by guillaume-uH57J9** [comment]
It does seem like a good idea to disable lazyShaders by default. 

Shader compilation is not asynchronous, so compiling shaders during the game would certainly cause frame drops. The exception being drivers that do shader cache, but that's not a perfect solution, and not all driver do it, so better not to rely upon the driver doing that. 

It's usually advised to compile shaders during initialization.
cf https://developer.apple.com/library/ios/documentation/3DDrawing/Conceptual/OpenGLES_ProgrammingGuide/BestPracticesforShaders/BestPracticesforShaders.html#//apple_ref/doc/uid/TP40008793-CH7-SW3

unvanquished docs say it's possible to do that when a map loads. That sounds like a good default. Because it would be possible to only compile shaders used for a specific map (and save memory, even if shader binaries are really big), and hopefully avoid frame drops.

**Comment by Viech** [comment]
The default should be *off*, which is why I'm wondering how it could be *on* for users who didn't explicitly enable it (or did you?): `r_lazyShaders = ri.Cvar_Get( "r_lazyShaders", "0", 0 );` (found [here](https://github.com/Unvanquished/Unvanquished/blob/master/src/engine/renderer/tr_init.cpp#L1118)).

**Comment by Veyrdite** [comment]
Lazyshaders has defaulted to 0 for me.  If anyone encounters this being set to '1' by default again (or still), please open a new bug report ala 'default cvar values not working'.
