### ISSUE TITLE
Error 0xc000007b when running a cross-compiled game on Windows

### ISSUE THREAD

**Issue by maek** [Unvanquished/Unvanquished#716]
Trying to run a cross-compiled executable (from Linux to Windows 7 64bit) leads to error 0xc000007b.
Here is the output of Dependency Walker:

![screenshot](https://cloud.githubusercontent.com/assets/121525/7493256/703668c6-f3ff-11e4-81c2-432177b19ed6.png)

If I copy the following files to the same folder where daemon.exe is located then it will run smooth:

/usr/x86_64-w64-mingw32/bin/libgcc_s_seh-1.dll
/usr/x86_64-w64-mingw32/bin/libstdc++-6.dll
/usr/x86_64-w64-mingw32/bin/libwinpthread-1.dll

What about making the build process include also these dlls in the build folder?

**Comment by Amanieu** [comment]
The problem here is that unlike the other dlls which are from our external_deps pacakges, these are provided by the mingw distribution and there is no way to automatically determine where to copy those from. The location and names of these dlls can vary between distributions or even different versions of mingw.

**Comment by maek** [comment]
Ok, then what about linking them statically?

**Comment by Amanieu** [comment]
Hmm that should be possible, I'll look into it

**Comment by slipher** [comment]
The Unvanquished [release script](https://github.com/Unvanquished/release-scripts/blob/master/build-release) can serve as documentation of which DLLs from mingw are needed. It also has a way (albeit a hacky one) to find the files. Look for the calls to `findDll`.
