### ISSUE TITLE
Little to no snow on Chasm

### ISSUE THREAD

**Issue by Kangz** [Unvanquished/Unvanquished#719]
![unvanquished_2015-05-07_044017_000](https://cloud.githubusercontent.com/assets/472810/7507649/2ea68c82-f473-11e4-803f-f537e912c7f1.jpg)

There used to have a lot of snow on Chasm but there isn't anymore see screenshot.
If you look at the sky closely you can see some flakes appear and disappear the frame after.

I am able to repro this consistently on Windows Mac and Linux, all three on recent Nvidia cards.

**Comment by Viech** [comment]
If I remember correctly you or @gimhael improved performance of particles recently? This could be the cause.

**Comment by Kangz** [comment]
I improved the perf on the VM -> Engine communication side but it is not likely to be the cause; people on IRC mentioned gimhael had a fix for this months ago but that it failed on windows 32 bit because of OOM.

**Comment by enneract** [comment]
How much snow there is supposed to be?

**Comment by Viech** [comment]
A lot more. I count three snowflakes on that screenshot, there should be hundreds.

**Comment by ckol** [comment]
Same on Arch Linux Unv 0.39.
Wondering how Chasm would look like when all the snow is gone?

**Comment by illwieckz** [comment]
On 0.50.0 I never seen any missing snow issue. I guess we can close?

**Comment by slipher** [comment]
I still don't see more than 2-3 snowflakes at any given time.

**Comment by Viech** [comment]
@Kangz and @slipher we need to know your hardware, and we then need @gimhael to see this issue as his particle changes seem to be a likely cause.

Personally I cannot reproduce on my Intel HD, I have to check again on my Nvidia at home.

**Comment by Kangz** [comment]
This was on a GTX670M, it will be a pain to try to reproduce on that computer but I can try on a newer NVIDIA card.

**Comment by slipher** [comment]
Radeon R7 200 here.

**Comment by illwieckz** [comment]
I'm very interested for a good measure of:

> How much snow there is supposed to be?

On my end (Radeon R9 390X on hardware side, amdgpu+radeonsi on software side) I see snowflakes, but I can't tell if I see less of them than I must be !

On the other hand, I tested Unvanquished on a NVidia GT210, while running the nvidia proprietary driver I get the #919 bug, while running on the free nouveau driver I get a weird effect I would exactly describe as “If you look at the sky closely you can see some flakes appear and disappear the frame after” with only one or two very rare snowflakes being visible when falling, sometime.

**Comment by Viech** [comment]
Maybe the particles collide right after they spawn.

**Comment by illwieckz** [comment]
I'm now able to run the NVidia GT210 on proprietary driver (with a workaround, see https://github.com/Unvanquished/Unvanquished/issues/919#issuecomment-353731852), and in this case I get the exact same flakes disappearing behavior on both `nouveau` and `nvidia` drivers.

Yeah, swaping completely the _software stack_ but using the same _hardware_ keeps the bug.

**Comment by slipher** [comment]
The hardware is also not a constant, since I saw a dearth of snowflakes on a Radeon card (mentioned above). I can now confirm that I see the same behavior with Nvidia and Intel GPUs: <5 snowflakes visible at a time. I used a recent version of the master branch for these last 2 observations.
For an estimate of the expected number of snowflakes, we can check the levelshot. I see more like 20-30 snowflakes rather than hundreds there, but clearly it is more than what I'm currently seeing.

**Comment by illwieckz** [comment]
Do you see the snowflakes disappearing on spawn?

**Comment by slipher** [comment]
If I decrease the max FPS I can see a few spots of light that quickly vanish, yes.

**Comment by illwieckz** [comment]
I I confirm I was also having the bug on my Radeon R9 390X (with mesa), there was less ”snowflakes disappearing” than on NVidia but there was enough to make it noticeable and I also seen the snowflakes disappearing while spawning. I just forgot to wrote it.

But today something changed, I got a lot of snow:

[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023415_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023415_000.jpg)
[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023426_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023426_000.jpg)
[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023431_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023431_000.jpg)
[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023436_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023436_000.jpg)
[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023447_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023447_000.jpg)
[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023508_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023508_000.jpg)
[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023558_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_023558_000.jpg)
[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_024017_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2018-03-07_024017_000.jpg)

I did these screenshots after having recompiled the chasm to test the reproduceability of our asset repositories, on latest for-0.51.0 Dæmon. So I first thought it was due to some map compilation thing.

But I started a prebuilt vanilla unvanquished 0.50.0 from unizip and loaded the official chasm map build… and I got the same.

I recently upgraded my graphic drivers from padoka stable ppa to unstable one.

Note that now the “indoor snowflake” bug is more noticeable, and I noticed for the first time there was no snowflakes in the outside part near human base. ;-)

**Comment by illwieckz** [comment]
The bug occurs when "Allow particles to bounce off surfaces" option is not activated (`cg_bounceParticles` set to `0` which is the default).

**Comment by illwieckz** [comment]
I have noticed the sky of chasm is a `common/slick` brush to prevent grangers to wallwalk, but that means it's also a clipping brush, it's also clipping weapon projectiles (see https://github.com/UnvanquishedAssets/map-chasm_src.dpkdir/issues/3 ) and is also buildable when extra `common/nobuild` brush is omitted (see https://github.com/UnvanquishedAssets/map-chasm_src.dpkdir/issues/4 ). I would not be surprised if it also clipped particles. On that screenshot the orange little boxes are the snowflakes generators:

[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/20210414-103133-000.netradiant-unvanquished-chasm-slick-snowflakes.png)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/20210414-103133-000.netradiant-unvanquished-chasm-slick-snowflakes.png)

Using 0.52 RC and `lowest` graphical preset that disables sky rendering and particle bouncing, we can see the particles properly falling from the sky and disappear where the slick brush is expected to be:

[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2021-04-12_083059_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2021-04-12_083059_000.jpg)

[![chasm snowflakes](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2021-04-12_083116_000.jpg)](https://dl.illwieckz.net/b/unvanquished/bugs/chasm-snowflakes/unvanquished_2021-04-12_083116_000.jpg)

**Comment by illwieckz** [comment]
This is now fixed. A special material named `common/slickplayerclip` was created to fit that use case.

**Comment by illwieckz** [comment]
This was an issue on asset side, unrelated to the renderer itself.

In fact the fact the snowflakes were successfully going through the sky for all those years when using `cg_bounceParticles` set to `1` may be a an engine bug, the same bug making some snowflakes going sometime through the solid ceiling…
