### ISSUE TITLE
Ubuntu Unity HUD prevents Unvanquished and other games to bind the <Alt> key

### ISSUE THREAD

**Issue by lamefun** [Unvanquished/Unvanquished#787]
When pressing the Alt key:

* The window is minimized.
* The `r_mode` variable, whatever it is, is set to `-1`, making the game launch in windowed mode the next time, even if the fullscreen option is enabled, so I have to set it back to `-2`.

Disabling the "Key to show the HUD" fixes the problem, but makes it impossible to use the new Ubuntu Alt functionality without either re-mapping it to another key or going to System Settings to disable/re-enable it before and after every Unvanquished play.

**Comment by illwieckz** [comment]
> but makes it impossible to use the new Ubuntu Alt functionality

What is this functionality?

Are you using the Unity dm? If yes, can you rename the issue title according to this. I'm on Ubuntu 15.04 too (with Gnome) and I don't experience this issue at all, it's probably an issue on your wm side.

**Comment by lamefun** [comment]
>What is this functionality?

Command search bar:

![Ubuntu HUD](http://4.bp.blogspot.com/-THp7LxwpKSc/T5jtnD3nrmI/AAAAAAAACr8/Nma5B472LaE/s1600/Ubuntu+HUD+Menus+12.04+Precise.png)

**Comment by illwieckz** [comment]
Your desktop environment assumes the <Alt> key is never used by applications, which is wrong, the bug is on your desktop-environment (Unity) side.

It's probably possible to workaround the problem if unvanquished captures the keyboard with exclusive access, but it's not desirable at all, remember the days when nobody where able to switch between their game and their desktop using `<Alt-Tab>` ? Nobody wants to turn back to the 90's.

I've installed Unity on a spare computer running Ubuntu 15.04 to reproduce the problem, the problem is reproduceable with all the games I tested, even PROprietary ones. The Unity command search bar brokes all games. Is Unvanquished the only game you play?

It's an Unity issue, please create a ticket on the Unity's bugzilla saying "please do not trigger the command search bar with the <Alt> key since it prevents users to bind the <Alt> key in their game, it's a critical regression, you broke thousands of games".

**Comment by illwieckz** [comment]
This issue is invalid.
