### ISSUE TITLE
bundling of various libraries

### ISSUE THREAD

**Issue by hasufell** [Unvanquished/Unvanquished#796]
Bundling of libararies is a serious QA issue for packagers and no 1 reason to not include something. Currently, I see two tarballs being fetched. One contains some nacl binaries and even clang/llvm libraries, the other freetype and libpng. Why is that?

**Comment by DolceTriade** [comment]
These are for convenience. They are nacl libraries specifically and are therefore crossplatform. You are free to build them yourself using nacl ports and then to set the appropriate variables in CMake.

**Comment by hasufell** [comment]
> You are free to build them yourself using nacl ports and then to set the appropriate variables in CMake.

Please be more specific. Which libraries/files exactly (and which version) and which variables? There's no convenient cmake option for that. Afais this is not just a single library, the tarball is stuffed with binaries and llvm stuff as well. See the file list: https://gist.github.com/hasufell/82a1bdcf8f929237482c

**Comment by Amanieu** [comment]
To build the tarballs yourself:
cd daemon/external_deps
./build.sh linux32 naclsdk naclports install package
./build.sh linux64 naclsdk naclports install package

**Comment by hasufell** [comment]
Uhm, that's not what I meant. Building 3rd party libraries during the unvanquished build is not a solution. They must be present on the system already.

**Comment by DolceTriade** [comment]
To be clear, these prebuilts are only required for building the crossplatform gamelogic .pexe modules. The native libs and executables will use the existing system libs. The only other issue from a packaging perspective would be the nacl_loader and the bootstrap binary. I'm not where you would build them from source and those are required to actually play the game

**Comment by Amanieu** [comment]
The nacl_loader, irt_core-x86_64.nexe and nacl_bootstrap_helper binaries are taken directly from the Native Client SDK. These are the only binaries from external_deps that are needed for packaging, since they are required at runtime. Everything else is only used to compile the VM code, which is distributed in pre-built .pk3 files.

The reason for downloading these during build time is that:
a) no linux distro that I know of has a package for the Native Client SDK
b) we require a very specific version of the SDK

**Comment by harmonise** [comment]
Closing. If there is a specific action that needs to be taken please re-open. Alternatively see issue #306
