### ISSUE TITLE
Empty map crash

### ISSUE THREAD

**Issue by mbasaglia** [Unvanquished/Unvanquished#849]
Creating a fake map pk3 can cause a segmentation fault.

Creating the pk3:

    touch foo && zip -p map-fubar_123.pk3 foo

Triggering the crash:

    /map vega (or whatever)
    (wait till loaded)
    /map fubar

Segmentation fault on SV_BuildClientSnapshot (dereferencing a null ps)

Notes: 
* It didn't crash with a dedicated server, it might need to have a connected client.
* Looks like calling map fubar from the menu tries to create a server even if there is no fubar.bsp, instead of giving the usual error "Can't find map fubar"
* The same happens if the pk3 contains an invalid bsp (`mkdir maps && touch maps/fubar.bsp && zip -p map-fubar_123.pk3 -r maps`) or if it isn't a proper pk3.

**Comment by Kangz** [comment]
So the problem was that some code was not handling the following path: Server restart -> Map load -> Sys::Drop -> SV_Shutdown -> send stuff to client. The client data was wiped during the server restart but the send stuff to client part was assuming that it was available.

This shows a whole class of problems that can appear when init and deinit can be reantrant because of Sys::Drop. I'm not sure how to fix it in a nice way, and this is when I'd love to have a Result<Success, Error> type instead of exceptions for errors:
