### ISSUE TITLE
Infuriating Grey Line

### ISSUE THREAD

**Issue by DolceTriade** [Unvanquished/Unvanquished#858]
![bug](http://i.imgur.com/xeQ9b8R.jpg)

It goes up the entire screen. It can be hidden behind geometry. I have confirmed that it is not being drawn by libRocket and am unsure about how to test it further.

**Comment by Viech** [comment]
Can you describe your feelings towards that line in more detail? Why does it make you angry?

Have you considered that it's an hardware issue?

**Comment by DolceTriade** [comment]
It makes me angry because its annoying :( It is most likely a hardware issue. I could not see it using my Intel drivers, but it shows up when I use bumblebee.

**Comment by cu-kai** [comment]
I get this too, it appears to be related to ssao.

**Comment by Kangz** [comment]
I don't see a problem in this picture :S

**Comment by Viech** [comment]
It's hard to verify given image compression artifacts, but raising contrast in the image may help you spot the slightly darker line on the dark grey surface marked with the red rectangle.

**Comment by jaytersen** [comment]
I've been doing a little digging on this one and come to the conclusion that this is a more general problem. If i turn ssao off, i can see an extremely faint discontinuity extending vertically down where the line used to be. It is almost as if a few "columns of pixels" are missing/skipped in the final rendered image. This also appears in the depth buffer which i believe is the reason we are getting some occlusion there.

**Comment by DolceTriade** [comment]
Interesting. So the issue is deep in the renderer?

**Comment by jaytersen** [comment]
It seems like it.

**Comment by IngarKCT** [comment]
I just saw the line on Vega, interestingly enough, it can be partially occluded by the globe, as if the line runs through it

**Comment by illwieckz** [comment]
Thinks like SSAO just helps to make the lines more obvious, but this is not related by SSAO.
I'm working on some dithering effect to reduce color banding ugliness, and dithering is basically noise, and I see the line. Well, I see the lines. I already seen the horizontal and vertical line before, but it's now more visible like that. Also, the far-right pixels are wrong too, but that other line is not really problematic in game.

[![boggy line](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_075655_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_075655_000.jpg)

I played with curves to make the noise more visible,
and added some `] [` around lines this way: `] | [`:

[![boggy lines](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_075655_001.jpg)](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_075655_001.jpg)

I sometime see another vertical line on the left.

Whith dithering and without ssao, the line may also give the illusion of distorting textures.

This screenshot with stock `0.51.1` build and ssao enabled reveals issue is not really about lines but about screen divided in square tiles, on this screenshot we even have a complete square tile being greyed out (top left), and we clearly see how the horizontal line is distorting the textures with ssao too:

[![boggy lines](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_085453_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_085453_000.jpg)

Here we can see the horizontal line, with some issues on the top left square, and we can notice the bottom edge of the top legt square is tilted:

[![boggy lines](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_090605_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_090605_000.jpg)

Because, yes, some lines may be neither horizontal, neither vertical, this screenshot shows an obvious horizontal line (jpg artifacts help), some tiles on the upper part, and a tilted line:

[![boggy lines](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_090631_000.jpg)](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/unvanquished_2020-02-09_090631_000.jpg)

To make the issues more obvious, images can be enlarged by clicking them.

**Comment by illwieckz** [comment]
@gimhael, the _tiled_ word rings a bell, can it be related to the _tiled_ renderer?

**Comment by DolceTriade** [comment]
This bug predates the tiled renderer.

**Comment by illwieckz** [comment]
Maybe I'm a wizard… [I may have fixed this bug](https://github.com/DaemonEngine/Daemon/pull/287). 👀

**Comment by slipher** [comment]
Is there some way to reliably reproduce the bug?

**Comment by illwieckz** [comment]
Get [this map](https://dl.illwieckz.net/b/daemon/bugs/boggy-lines/map-metro_0~0-boggy-lines.dpk).

Set this in game (I get the worst results with that resolution) and load the map:

```
r_FXAA 1
r_ssao 1
r_customwidth 2560
r_customheight 1440
devmap metro
```

Then fly around the walls, above the lamp, close to the wall, then look at tiled white textures.
