### ISSUE TITLE
Server Ping Higher Than Normal

### ISSUE THREAD

**Issue by RealCh4mp** [Unvanquished/Unvanquished#970]
There's about 15-20 higher ping with the current git than stable 0.8.1.

When I ping my server it's only 45ms and ingame it's 60 - 70 or even higher.

**Comment by illwieckz** [comment]
`0.8.1` version suggests a xonotic issue, the xonotic issue tracker is there:
https://gitlab.com/xonotic/netradiant/issues

By the way, I don't think an unusual higher ping on your side would be an acceptable issue (unless you have serious material that proves a regression) because it's just hard to reproduce, and ping variation is very common.

**Comment by illwieckz** [comment]
Well, it looks like you found it:
https://gitlab.com/xonotic/darkplaces/issues/108
https://gitlab.com/xonotic/darkplaces/issues/109
